/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author prachisilwal
 */
public class User_Registration extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(User_Registration.class.getName());

    /**
     * Creates new form User_Registration
     */
    public User_Registration() {
        initComponents();
        Register.addActionListener(this::RegisterActionPerformed);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

@SuppressWarnings("unchecked") 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        logo = new javax.swing.JLabel();
        box = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        Company = new javax.swing.JButton();
        underline_seeker = new javax.swing.JPanel();
        Seeker = new javax.swing.JButton();
        Full_Name = new javax.swing.JLabel();
        user_type_Full_Name = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        user_username_ = new javax.swing.JTextField();
        Contact = new javax.swing.JLabel();
        user_type_contact = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        user_type_Email = new javax.swing.JTextField();
        Address = new javax.swing.JLabel();
        user_type_Address = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        user_type_Password = new javax.swing.JPasswordField();
        Reenter_password = new javax.swing.JLabel();
        user_type_Reenter_Password = new javax.swing.JPasswordField();
        Register = new javax.swing.JButton();
        login_here = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/98159746-5A93-446F-97EE-9D6082B19BC5_4_5005_c.jpeg"))); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(10, 10, 100, 100);

        box.setBackground(new java.awt.Color(57, 174, 221));
        box.setLayout(null);

        Heading.setBackground(new java.awt.Color(43, 219, 43));
        Heading.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading.setText("RENT YOUR ADVENTURE");
        Heading.setOpaque(true);
        box.add(Heading);
        Heading.setBounds(100, 10, 330, 50);

        Company.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        Company.setText("Company");
        Company.setIconTextGap(5);
        Company.addActionListener(this::CompanyActionPerformed);
        box.add(Company);
        Company.setBounds(30, 70, 160, 35);

        underline_seeker.setBackground(new java.awt.Color(0, 0, 0));
        underline_seeker.setLocation(new java.awt.Point(330, 103));
        underline_seeker.setMinimumSize(new java.awt.Dimension(10, 3));
        box.add(underline_seeker);
        underline_seeker.setBounds(30, 103, 160, 3);

        Seeker.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        Seeker.setText("Seeker");
        Seeker.setIconTextGap(5);
        Seeker.addActionListener(this::SeekerActionPerformed);
        box.add(Seeker);
        Seeker.setBounds(330, 70, 160, 35);

        Full_Name.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Full_Name.setText("Full Name                :");
        box.add(Full_Name);
        Full_Name.setBounds(30, 130, 140, 30);

        user_type_Full_Name.addActionListener(this::user_type_Full_NameActionPerformed);
        box.add(user_type_Full_Name);
        user_type_Full_Name.setBounds(180, 130, 330, 30);

        username.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        username.setText("username_              :");
        box.add(username);
        username.setBounds(30, 180, 140, 30);
        box.add(user_username_);
        user_username_.setBounds(180, 180, 330, 30);

        Contact.setText("Contact no.               :");
        box.add(Contact);
        Contact.setBounds(30, 230, 140, 30);
        box.add(user_type_contact);
        user_type_contact.setBounds(180, 230, 330, 30);

        Email.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Email.setText("Email                       :");
        box.add(Email);
        Email.setBounds(30, 280, 140, 30);
        box.add(user_type_Email);
        user_type_Email.setBounds(180, 280, 330, 30);

        Address.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Address.setText("Address                   :");
        box.add(Address);
        Address.setBounds(30, 330, 140, 30);
        box.add(user_type_Address);
        user_type_Address.setBounds(180, 330, 330, 30);

        Password.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Password.setText("Password                :");
        box.add(Password);
        Password.setBounds(30, 380, 140, 30);
        box.add(user_type_Password);
        user_type_Password.setBounds(180, 430, 330, 30);

        Reenter_password.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Reenter_password.setText("Re-enter password  :");
        box.add(Reenter_password);
        Reenter_password.setBounds(30, 430, 140, 30);
        box.add(user_type_Reenter_Password);
        user_type_Reenter_Password.setBounds(180, 380, 330, 30);

        getContentPane().add(box);
        box.setBounds(20, 130, 520, 480);

        Register.setBackground(new java.awt.Color(0, 191, 239));
        Register.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        Register.setText("Register");
        getContentPane().add(Register);
        Register.setBounds(190, 626, 150, 40);

        login_here.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        login_here.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_here.setText("Already have account? Login here.");
        getContentPane().add(login_here);
        login_here.setBounds(160, 670, 230, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User Registration image.png"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>                        

    private void user_type_Full_NameActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void CompanyActionPerformed(java.awt.event.ActionEvent evt) {                                        
        Company_Registration company = new Company_Registration();
        company.setVisible(true);
        this.dispose();
    }                                       

    private void SeekerActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new User_Registration().setVisible(true));
    }
    
        private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {
        String fullname = user_type_Full_Name.getText();
        String username = user_username_.getText();
        String contact = user_type_contact.getText();
        String email = user_type_Email.getText();
        String address = user_type_Address.getText();
        String password = new String(user_type_Password.getPassword());
        String rePassword = new String(user_type_Reenter_Password.getPassword());

        if (fullname.isEmpty() || username.isEmpty() || contact.isEmpty() || email.isEmpty() || address.isEmpty() || password.isEmpty() || rePassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        if (!password.equals(rePassword)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match.");
            return;
        }
        
            try {
        // Adjust these as per your MySQL setup
        String url = "jdbc:mysql://localhost:3306/yourdatabase";
        String dbUser = "root";
        String dbPass = "mydadaisgreat";

        Connection conn = DriverManager.getConnection(url, dbUser, dbPass);

        String sql = "INSERT INTO users (fullname, username, contact, email, address, password) VALUES (?, ?, ?, ?, ?, ?)";

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, fullname);
        pst.setString(2, username);
        pst.setString(3, contact);
        pst.setString(4, email);
        pst.setString(5, address);
        pst.setString(6, password); 

        int inserted = pst.executeUpdate();

        if (inserted > 0) {
            JOptionPane.showMessageDialog(this, "Registration successful!");
          
        } else {
            JOptionPane.showMessageDialog(this, "Registration failed.");
        }

        pst.close();
        conn.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        logger.log(java.util.logging.Level.SEVERE, "Database insertion error", e);
    }
}


    // Variables declaration - do not modify                     
    private javax.swing.JLabel Address;
    private javax.swing.JButton Company;
    private javax.swing.JLabel Contact;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Full_Name;
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Reenter_password;
    private javax.swing.JButton Register;
    private javax.swing.JButton Seeker;
    private javax.swing.JLabel background;
    private javax.swing.JPanel box;
    private javax.swing.JLabel login_here;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel underline_seeker;
    private javax.swing.JTextField user_type_Address;
    private javax.swing.JTextField user_type_Email;
    private javax.swing.JTextField user_type_Full_Name;
    private javax.swing.JPasswordField user_type_Password;
    private javax.swing.JPasswordField user_type_Reenter_Password;
    private javax.swing.JTextField user_type_contact;
    private javax.swing.JTextField user_username_;
    private javax.swing.JLabel username;
    // End of variables declaration                   
}
