/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;
import javax.swing.*;
import java.sql.*;

 /**
 * 
 * @author prachisilwal
 */
public class User_Registration extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(User_Registration.class.getName());
    private JCheckBox showPasswordUser;
    private JCheckBox showRePasswordUser;
    private char defaultEchoCharUser;
    private char defaultReEchoCharUser;
    
    /**
     * Creates new form User_Registration
     */
public User_Registration() {
    initComponents();
    setLocationRelativeTo(null);

    // store default echo chars
    defaultEchoCharUser = user_type_Password.getEchoChar();
    defaultReEchoCharUser = user_type_Reenter_Password.getEchoChar();

    // Show/hide password checkbox
    showPasswordUser = new JCheckBox("Show");
    showPasswordUser.setBounds(520, 430, 80, 30);
    box.add(showPasswordUser);
    showPasswordUser.addActionListener(e -> {
        user_type_Password.setEchoChar(showPasswordUser.isSelected() ? (char)0 : defaultEchoCharUser);
        user_type_Password.repaint();
    });

    // Show/hide re-enter password checkbox
    showRePasswordUser = new JCheckBox("Show");
    showRePasswordUser.setBounds(520, 380, 80, 30);
    box.add(showRePasswordUser);
    showRePasswordUser.addActionListener(e -> {
        user_type_Reenter_Password.setEchoChar(showRePasswordUser.isSelected() ? (char)0 : defaultReEchoCharUser);
        user_type_Reenter_Password.repaint();
    });
   
    // Make "Login here" clickable
    login_here.setText("<html><nobr>Already have an account? <u><font color='blue'>Login here</font></u></nobr></html>");
    login_here.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    login_here.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            JOptionPane.showMessageDialog(
                User_Registration.this,
                "Login page will be connected after module integration."
            );
        }
    });

    Register.addActionListener(this::RegisterActionPerformed);

    Company.addActionListener(evt -> {
        new Company_Registration().setVisible(true);
        this.dispose();
    });
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

@SuppressWarnings("unchecked") 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        logo = new javax.swing.JLabel();
        box = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        underline_seeker = new javax.swing.JPanel();
        Company = new javax.swing.JButton();
        Seeker = new javax.swing.JButton();
        Full_Name = new javax.swing.JLabel();
        user_type_Full_Name = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        user_username_ = new javax.swing.JTextField();
        Contact = new javax.swing.JLabel();
        user_type_contact = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        user_type_Email = new javax.swing.JTextField();
        Address = new javax.swing.JLabel();
        user_type_Address = new javax.swing.JTextField();
        pass_checkbox = new javax.swing.JCheckBox();
        Password = new javax.swing.JLabel();
        user_type_Password = new javax.swing.JPasswordField();
        reenter_checkbox = new javax.swing.JCheckBox();
        Reenter_password = new javax.swing.JLabel();
        user_type_Reenter_Password = new javax.swing.JPasswordField();
        Register = new javax.swing.JButton();
        login_here = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/98159746-5A93-446F-97EE-9D6082B19BC5_4_5005_c.jpeg"))); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(10, 10, 100, 100);

        box.setBackground(new java.awt.Color(57, 174, 221));
        box.setLayout(null);

        Heading.setBackground(new java.awt.Color(43, 219, 43));
        Heading.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading.setText("RENT YOUR ADVENTURE");
        Heading.setOpaque(true);
        box.add(Heading);
        Heading.setBounds(100, 10, 330, 50);

        underline_seeker.setBackground(new java.awt.Color(0, 0, 0));
        underline_seeker.setMinimumSize(new java.awt.Dimension(10, 3));
        box.add(underline_seeker);
        underline_seeker.setBounds(330, 103, 160, 3);

        Company.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        Company.setText("Company");
        Company.setIconTextGap(5);
        Company.addActionListener(this::CompanyActionPerformed);
        box.add(Company);
        Company.setBounds(30, 70, 160, 35);

        Seeker.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        Seeker.setText("Seeker");
        Seeker.setIconTextGap(5);
        Seeker.addActionListener(this::SeekerActionPerformed);
        box.add(Seeker);
        Seeker.setBounds(330, 70, 160, 35);

        Full_Name.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Full_Name.setText("Full Name                :");
        box.add(Full_Name);
        Full_Name.setBounds(30, 130, 140, 30);

        user_type_Full_Name.addActionListener(this::user_type_Full_NameActionPerformed);
        box.add(user_type_Full_Name);
        user_type_Full_Name.setBounds(180, 130, 330, 30);

        username.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        username.setText("username_              :");
        box.add(username);
        username.setBounds(30, 180, 140, 30);
        box.add(user_username_);
        user_username_.setBounds(180, 180, 330, 30);

        Contact.setText("Contact no.               :");
        box.add(Contact);
        Contact.setBounds(30, 230, 140, 30);
        box.add(user_type_contact);
        user_type_contact.setBounds(180, 230, 330, 30);

        Email.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Email.setText("Email                       :");
        box.add(Email);
        Email.setBounds(30, 280, 140, 30);
        box.add(user_type_Email);
        user_type_Email.setBounds(180, 280, 330, 30);

        Address.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Address.setText("Address                   :");
        box.add(Address);
        Address.setBounds(30, 330, 140, 30);
        box.add(user_type_Address);
        user_type_Address.setBounds(180, 330, 330, 30);

        pass_checkbox.addActionListener(this::pass_checkboxActionPerformed);
        box.add(pass_checkbox);
        pass_checkbox.setBounds(485, 435, 19, 20);

        Password.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Password.setText("Password                :");
        box.add(Password);
        Password.setBounds(30, 380, 140, 30);
        box.add(user_type_Password);
        user_type_Password.setBounds(180, 430, 330, 30);

        reenter_checkbox.addActionListener(this::reenter_checkboxActionPerformed);
        box.add(reenter_checkbox);
        reenter_checkbox.setBounds(485, 385, 19, 20);

        Reenter_password.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Reenter_password.setText("Re-enter password  :");
        box.add(Reenter_password);
        Reenter_password.setBounds(30, 430, 140, 30);
        box.add(user_type_Reenter_Password);
        user_type_Reenter_Password.setBounds(180, 380, 330, 30);

        getContentPane().add(box);
        box.setBounds(20, 150, 520, 480);

        Register.setBackground(new java.awt.Color(0, 191, 239));
        Register.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        Register.setText("Register");
        Register.addActionListener(this::RegisterActionPerformed);
        getContentPane().add(Register);
        Register.setBounds(190, 660, 150, 40);

        login_here.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        login_here.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_here.setText("Already have account? Login here.");
        getContentPane().add(login_here);
        login_here.setBounds(160, 710, 250, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User Registration image.png"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, 0, 1370, 770);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void user_type_Full_NameActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void CompanyActionPerformed(java.awt.event.ActionEvent evt) {                                        
        Company_Registration company = new Company_Registration();
        company.setVisible(true);
        this.dispose();
    }                                       
    private Company_Registration companylogin;
    private void SeekerActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
      if (companylogin==null){
          companylogin =new Company_Registration ();
          companylogin.setSize(1366,768);
      }  
      if (companylogin.isVisible()){
          companylogin.setVisible(false);
      }else
          companylogin.setVisible(true);
          companylogin.toFront();
        
    }                                      

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String fullName = user_type_Full_Name.getText();
        String username = user_username_.getText();
        String contact = user_type_contact.getText();
        String email = user_type_Email.getText();
        String address = user_type_Address.getText();
        String password = new String(user_type_Password.getPassword());
        String rePassword = new String(user_type_Reenter_Password.getPassword());

        if (fullName.isEmpty() || username.isEmpty() || contact.isEmpty() || email.isEmpty() || address.isEmpty() || password.isEmpty() || rePassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        if (!password.equals(rePassword)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match.");
            return;
        }

        // TODO: Ideally hash the password here before storing.
        
        try {
            String url = "jdbc:mysql://localhost:3306/yourdatabase";
            String dbUser = "root";
            String dbPass = "mydadaisgreat";
            
            Connection conn = DriverManager.getConnection(url, dbUser, dbPass);

            String sql = "INSERT INTO customers (full_name, username, contact_no, email, address, password) VALUES (?, ?, ?, ?, ?, ?)";

            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, fullName);
            pst.setString(2, username);
            pst.setString(3, contact);
            pst.setString(4, email);
            pst.setString(5, address);
            pst.setString(6, password);

            int inserted = pst.executeUpdate();

            if (inserted > 0) {
                JOptionPane.showMessageDialog(this, "User registered successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Registration failed.");
            }

            pst.close();
            conn.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
            e.printStackTrace();
        }
    

    }                                        

    private void pass_checkboxActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void reenter_checkboxActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                
    
    public static void main(String[] args) {
    java.awt.EventQueue.invokeLater(() -> {
        new User_Registration().setVisible(true);
    });
}


    // Variables declaration - do not modify                     
    private javax.swing.JLabel Address;
    private javax.swing.JButton Company;
    private javax.swing.JLabel Contact;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Full_Name;
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Reenter_password;
    private javax.swing.JButton Register;
    private javax.swing.JButton Seeker;
    private javax.swing.JLabel background;
    private javax.swing.JPanel box;
    private javax.swing.JLabel login_here;
    private javax.swing.JLabel logo;
    private javax.swing.JCheckBox pass_checkbox;
    private javax.swing.JCheckBox reenter_checkbox;
    private javax.swing.JPanel underline_seeker;
    private javax.swing.JTextField user_type_Address;
    private javax.swing.JTextField user_type_Email;
    private javax.swing.JTextField user_type_Full_Name;
    private javax.swing.JPasswordField user_type_Password;
    private javax.swing.JPasswordField user_type_Reenter_Password;
    private javax.swing.JTextField user_type_contact;
    private javax.swing.JTextField user_username_;
    private javax.swing.JLabel username;
    // End of variables declaration                   
}
