/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import database.MySqlConnection;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;

/**
 *
 * @author hp
 */
public class request extends javax.swing.JPanel {
    // 1. ADD THIS FIELD: To hold the reference to the main list frame
    private VehicleRequest mainFrame;
    /**
     * Creates new form request
     */
    
    public request() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.BLACK));
       
    }
    // 2. ADD THIS SETTER: So VehicleRequest can pass itself to this row
    public void setMainFrame(VehicleRequest frame) {
        this.mainFrame = frame;
    }
    
    public void setShortData(String name, String plate, String priceValue, String companyId) {
    model.setText(name);      
    jLabel1.setText("Vec.ID :"+plate);   
    // Appending " / Day" or " / Hr" to the price label
    price.setText("Rs. " + priceValue + "/Day"); 
    jLabel2.setText("Comp.ID :"+companyId);
}
    // 2. This is the logic for when the admin clicks "View"



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        model = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        view = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(865, 60));
        setMinimumSize(new java.awt.Dimension(865, 60));
        setPreferredSize(new java.awt.Dimension(865, 60));
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                formAncestorRemoved(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        model.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        model.setText("Name");
        add(model, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 60));

        price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        price.setText("Price");
        add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 110, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("NumberPlate");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 190, -1));

        view.setBackground(new java.awt.Color(51, 255, 51));
        view.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        view.setText("View");
        view.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 90, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Company ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorRemoved
   
    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
         String plateNumber = jLabel1.getText().replace("Vec.ID :", "").trim();
    // 1. Fetching all details including company_id and price
    String sql = "SELECT * FROM vehicleDetails WHERE numberPlate = ?";

    try (Connection conn = MySqlConnection.getInstance().getConnection();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {
        
        pstmt.setString(1, plateNumber);
        ResultSet rs = pstmt.executeQuery();

        if (rs.next()) {
            // Create the detail panel instance
            viewvehicle_details detailsPanel = new viewvehicle_details();
            
            // 2. IMPORTANT: Pass the mainFrame reference to the details panel
            // This allows the details panel to call loadRequestsFromDB() later
            detailsPanel.setParentFrame(this.mainFrame);
            
            // Convert BLOBs to temporary files for display
            File frontImg = saveBlobToTempFile(rs.getBlob("image_front"), "front_" + plateNumber);
            File sideImg = saveBlobToTempFile(rs.getBlob("image_side"), "side_" + plateNumber);

            // 2. Format the price and company ID display
            String formattedPrice = "Rs. " + rs.getString("price") + "/Day";
            String companyInfo = rs.getString("company_id"); // Ensure this column exists in DB

            // 3. Pass data to detailsPanel
            // NOTE: If you want to show Company ID in the big window, 
            // you should update the setVehicleData method in viewvehicle_details.java too!
            detailsPanel.setVehicleData(
                rs.getString("brand"),
                rs.getString("model"),
                rs.getString("type"),
                rs.getString("colour"),
                plateNumber,
                formattedPrice,
                frontImg,
                sideImg
            );

            // 4. Setup and Show the Window
            javax.swing.JFrame detailWindow = new javax.swing.JFrame("Review Vehicle: " + plateNumber + " (ID: " + companyInfo + ")");
            detailWindow.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
            detailWindow.add(detailsPanel);
            detailWindow.pack();
            detailWindow.setSize(940, 700);
            detailWindow.setLocationRelativeTo(null);
            detailWindow.setVisible(true);
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error fetching full details: " + e.getMessage());
    }
    } // <--- THIS BRACE CLOSES viewActionPerformed

    // This method MUST be outside of viewActionPerformed
    private File saveBlobToTempFile(java.sql.Blob blob, String prefix) throws Exception {
        if (blob == null) return null;
        
        File tempFile = File.createTempFile(prefix, ".jpg");
        tempFile.deleteOnExit(); 
        
        // Correct Try-with-resources syntax
        try (InputStream is = blob.getBinaryStream();
             FileOutputStream fos = new FileOutputStream(tempFile)) {
            
            byte[] buffer = new byte[4096];
            int bytesRead;
            while ((bytesRead = is.read(buffer)) != -1) {
                fos.write(buffer, 0, bytesRead);
            }
        } 
        return tempFile;
       
    
        
        
    
    }//GEN-LAST:event_viewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel model;
    private javax.swing.JLabel price;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
public static void main(String[] args) {
    javax.swing.JFrame frame = new javax.swing.JFrame();
    frame.add(new request()); // Add your panel to a new window
    frame.pack();
    frame.setSize(800, 100); // Give it a small size since it's a list item
    frame.setLocationRelativeTo(null);
    frame.setVisible(true);
    
}
}
