/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import UserController.admin_VehicleRequestController;
import javax.swing.SwingUtilities;

/**
 *
 * @author hp
 */
public class admin_vehiclerequestitems extends javax.swing.JPanel {

    private admin_VehicleRequest mainFrame;

    public admin_vehiclerequestitems() {
        initComponents();
        setupAppearance();
    }

    private void setupAppearance() {
        // Bottom border separator for visual clarity between items
        this.setBorder(
            javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.LIGHT_GRAY)
        );
    }

    /**
     * Associates this item with the parent frame to access the main controller.
     */
    public void setMainFrame(admin_VehicleRequest frame) {
        this.mainFrame = frame;
    }

    /**
     * Populates the labels with vehicle data.
     */
    public void setShortData(String name, String plate, String priceValue, String companyId) {
        SwingUtilities.invokeLater(() -> {
            model.setText(name != null ? name : "Unknown Vehicle");
            jLabel1.setText("Vec.ID : " + (plate != null ? plate : "N/A"));
            price.setText("Rs. " + (priceValue != null ? priceValue : "0") + "/Day");
            jLabel2.setText("Comp.ID : " + (companyId != null ? companyId : "N/A"));
        });
    

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        model = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        view = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(865, 60));
        setMinimumSize(new java.awt.Dimension(865, 60));
        setPreferredSize(new java.awt.Dimension(865, 60));
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                formAncestorRemoved(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        model.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        model.setText("Name");
        add(model, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 60));

        price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        price.setText("Price");
        add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 110, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("NumberPlate");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 190, -1));

        view.setBackground(new java.awt.Color(51, 255, 51));
        view.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        view.setText("View");
        view.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 90, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Company ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorRemoved
   
    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
       // 1. Extract the plate number from the label accurately
        String plateLabel = jLabel1.getText();
        if (!plateLabel.contains("Vec.ID :")) return;
        
        String plateNumber = plateLabel.replace("Vec.ID :", "").trim();
        
        // 2. Delegate the detail view logic to the existing main controller
        if (mainFrame != null) {
            admin_VehicleRequestController controller = mainFrame.getController();
            if (controller != null) {
                controller.handleViewDetails(plateNumber, mainFrame);
            }
        } else {
            java.util.logging.Logger.getLogger(admin_vehiclerequestitems.class.getName())
                .log(java.util.logging.Level.SEVERE, "Parent frame reference is missing.");
        }
    
    }//GEN-LAST:event_viewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel model;
    private javax.swing.JLabel price;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables

}
