/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import database.MySqlConnection;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author hp
 */
public class viewvehicle_details extends javax.swing.JPanel {
   
    /**
     * Creates new form viewvehicle_details
     */

    private VehicleRequest parentFrame;
    public viewvehicle_details() {
        initComponents();
    }
    // 2. ADD THIS SETTER TO THE CLASS
    public void setParentFrame(VehicleRequest parent) {
        this.parentFrame = parent;
    }
    // Inside viewvehicle_details class
public void setVehicleData(String brand, String model, String type, String color, String plate, String price, java.io.File frontImg, java.io.File sideImg) {
    jLabel9.setText(brand);
    jLabel10.setText(model);
    jLabel11.setText(type);
    jLabel12.setText(color);
    jLabel13.setText(plate);
    jLabel2.setText(price);

    // Set Front Image
    if (frontImg != null) {
        displayImage(frontImg, lblImage1);
    }
    // Set Side Image
    if (sideImg != null) {
        displayImage(sideImg, lblImage2);
    }
}

// Helper method to scale images for the admin labels
private void displayImage(java.io.File file, javax.swing.JLabel label) {
   javax.swing.ImageIcon icon = new javax.swing.ImageIcon(file.getAbsolutePath());
    
    // If width is 0, use the design width of 400
    int width = label.getWidth() > 0 ? label.getWidth() : 400;
    int height = label.getHeight() > 0 ? label.getHeight() : 300;
    
    java.awt.Image img = icon.getImage().getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH);
    label.setIcon(new javax.swing.ImageIcon(img));
    label.setText("");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblImage2 = new javax.swing.JLabel();
        lblImage1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 204, 255));
        setMaximumSize(new java.awt.Dimension(920, 650));
        setMinimumSize(new java.awt.Dimension(920, 650));
        setPreferredSize(new java.awt.Dimension(920, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Brand               :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 110, 16));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("model               :  ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 115, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Vehicle  Type   :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 110, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Colour              :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 110, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Number Plate  :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 110, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Price                 :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 110, -1));

        lblImage2.setBackground(new java.awt.Color(255, 255, 255));
        lblImage2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblImage2.setForeground(new java.awt.Color(255, 255, 255));
        lblImage2.setText("                           insert Side photo  ");
        lblImage2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        lblImage2.setMaximumSize(new java.awt.Dimension(400, 300));
        lblImage2.setPreferredSize(new java.awt.Dimension(400, 300));
        add(lblImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, -1));

        lblImage1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblImage1.setForeground(new java.awt.Color(255, 255, 255));
        lblImage1.setText("         insert Front photo with number plate");
        lblImage1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        lblImage1.setMinimumSize(new java.awt.Dimension(400, 300));
        lblImage1.setPreferredSize(new java.awt.Dimension(400, 300));
        add(lblImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Vehicle details");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(110, 10, 180, 30);

        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(160, 260, 220, 16);

        jLabel9.setText("jLabel2");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(160, 60, 220, 16);

        jLabel10.setText("jLabel2");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(160, 100, 220, 16);

        jLabel11.setText("jLabel2");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(160, 140, 220, 16);

        jLabel12.setText("jLabel2");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(160, 180, 220, 16);

        jLabel13.setText("jLabel2");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(160, 220, 220, 16);

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Reject");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(250, 370, 80, 30);

        jButton2.setBackground(new java.awt.Color(51, 255, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Accept");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(30, 370, 80, 30);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 400, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      // 1. Get the plate number
    String plate = jLabel13.getText().trim();

    // 2. Add a Confirmation Dialog so it's not accidental
    int response = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to APPROVE this vehicle?", 
            "Confirm Approval", 
            javax.swing.JOptionPane.YES_NO_OPTION);

    if (response == javax.swing.JOptionPane.YES_OPTION) {
        try {
            java.sql.Connection conn = database.MySqlConnection.getInstance().getConnection();
            
            // 3. Update Status
            // Note: If your vehicleinfo list looks for 'accepted', use 'accepted' here.
            String sql = "UPDATE vehicleDetails SET status = 'approved', rejection_reason = NULL WHERE numberPlate = ?";
            
            java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, plate);

            int rowsUpdated = pstmt.executeUpdate();

            if (rowsUpdated > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Vehicle Approved Successfully!");
                
                // 4. Refresh the main list and close this window
                refreshAndClose(); 
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: Vehicle record not found.");
            }
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int response = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to reject this vehicle?", "Confirm Rejection", 
            JOptionPane.YES_NO_OPTION);
            
        if (response == JOptionPane.YES_OPTION) {
            String reason = JOptionPane.showInputDialog(this, "Enter reason for rejection:");

            if (reason == null) return; 
            if (reason.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "A reason is required to reject a vehicle.");
                return;
            }

            String plate = jLabel13.getText().trim();
            
            try {
                Connection conn = MySqlConnection.getInstance().getConnection();
                String sql = "UPDATE vehicleDetails SET status = 'rejected', rejection_reason = ? WHERE numberPlate = ?";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, reason.trim());
                pstmt.setString(2, plate);
                
                if (pstmt.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(this, "Vehicle Rejected.");
                    refreshAndClose();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage() + 
                    "\n(Check if 'rejection_reason' column exists in your DB)");
            }
        }
    }
    // Helper to refresh the list and close the current window
    private void refreshAndClose() {
        if (parentFrame != null) {
            // Passing empty string to load all pending requests again
            parentFrame.loadRequests(""); 
        }
        // Closes the JFrame that contains this JPanel
        SwingUtilities.getWindowAncestor(this).dispose();
    


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblImage1;
    private javax.swing.JLabel lblImage2;
    // End of variables declaration//GEN-END:variables
public static void main(String[] args) {
    javax.swing.JFrame frame = new javax.swing.JFrame();
    frame.setContentPane(new viewvehicle_details()); // Put your panel in a window
    frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
    frame.pack();
    frame.setSize(920, 670);
    frame.setLocationRelativeTo(null);
    frame.setVisible(true);
}
}
