/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import dao.BookingHistoryDAO;
import model.VehicleBooking;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author WELCOME
 */
public class Booking_History extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Booking_History.class.getName());

    /**
     * Creates new form Booking_History
     */
    public Booking_History() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bookinghistory = new javax.swing.JLabel();
        customer_ = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        loadbooking = new javax.swing.JButton();
        viewdetails = new javax.swing.JButton();
        back = new javax.swing.JButton();
        customer = new javax.swing.JLabel();
        search1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        getContentPane().setLayout(null);

        Bookinghistory.setFont(new java.awt.Font("High Tower Text", 1, 36)); // NOI18N
        Bookinghistory.setText("Booking History");
        getContentPane().add(Bookinghistory);
        Bookinghistory.setBounds(300, 20, 380, 60);

        customer_.addActionListener(this::customer_ActionPerformed);
        getContentPane().add(customer_);
        customer_.setBounds(370, 110, 120, 22);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Booking ID", "Customer Name", "Pickup Date ", "Return Date", "Pickup Location", "Return Location", "Driver Option"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 180, 700, 320);

        loadbooking.setBackground(new java.awt.Color(0, 102, 51));
        loadbooking.setForeground(new java.awt.Color(255, 255, 255));
        loadbooking.setText("Load Booking");
        loadbooking.addActionListener(this::loadbookingActionPerformed);
        getContentPane().add(loadbooking);
        loadbooking.setBounds(220, 560, 110, 23);

        viewdetails.setBackground(new java.awt.Color(0, 102, 51));
        viewdetails.setForeground(new java.awt.Color(255, 255, 255));
        viewdetails.setText("View Details");
        getContentPane().add(viewdetails);
        viewdetails.setBounds(370, 560, 110, 23);

        back.setBackground(new java.awt.Color(51, 153, 255));
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(this::backActionPerformed);
        getContentPane().add(back);
        back.setBounds(530, 560, 72, 23);

        customer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customer.setText("Search By Customer:");
        getContentPane().add(customer);
        customer.setBounds(230, 110, 130, 20);

        search1.setBackground(new java.awt.Color(0, 102, 51));
        search1.setForeground(new java.awt.Color(255, 255, 255));
        search1.setText("Search");
        search1.addActionListener(this::search1ActionPerformed);
        getContentPane().add(search1);
        search1.setBounds(510, 110, 70, 23);

        setBounds(0, 0, 934, 658);
    }// </editor-fold>//GEN-END:initComponents

    private void customer_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseReleased

    private void loadbookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadbookingActionPerformed
        // TODO add your handling code here:
       BookingHistoryDAO dao = new BookingHistoryDAO();
       List<VehicleBooking> list = dao.getAllBookingHistory();

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    for (VehicleBooking v : list) {
            model.addRow(new Object[]{
                    v.bookingId,
                    v.fullName,
                    v.pickupDate,
                    v.returnDate,
                    v.pickupLocation,
                    v.returnLocation,
                    v.driverOption
            });
        }
    }//GEN-LAST:event_loadbookingActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        // TODO add your handling code here:
        // 1. Get text from search field
    String customerName = customer_.getText().trim();

    // 2. Validation
    if (customerName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter customer name");
        return;
    }

    // 3. Call DAO
    BookingHistoryDAO dao = new BookingHistoryDAO();
    List<VehicleBooking> list = dao.searchByCustomerName(customerName);

    // 4. Load data into table
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    for (VehicleBooking v : list) {
        model.addRow(new Object[]{
            v.bookingId,
            v.fullName,
            v.pickupDate,
            v.returnDate,
            v.pickupLocation,
            v.returnLocation,
            v.driverOption
        });
    }

    // 5. If no data found
    if (list.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No record found");
    }
    }//GEN-LAST:event_search1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Booking_History().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bookinghistory;
    private javax.swing.JButton back;
    private javax.swing.JLabel customer;
    private javax.swing.JTextField customer_;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton loadbooking;
    private javax.swing.JButton search1;
    private javax.swing.JButton viewdetails;
    // End of variables declaration//GEN-END:variables
}
