/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.awt.Color;
import UserController.CompanyDashboardController; // Ensure this matches your package name
import javax.swing.*; 
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author hp
 */
public class CompanyDashboard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CompanyDashboard.class.getName());

    /**
     * Creates new form CompanyDashboard
     */
    private int companyId;
    private javax.swing.Timer refreshTimer;
    private CompanyDashboardController controller;
     
    
    public CompanyDashboard(int companyId) {
        this.companyId = companyId;
        initComponents();
        
        // Initialize the controller
        this.controller = new CompanyDashboardController(this); 
        
        // UI Styling
        jTable1.setRowHeight(30);
        jTable1.getTableHeader().setBackground(new Color(102, 204, 255));
        
        // Initial Data Load
        controller.refreshTable(this.companyId);
        startAutoRefresh();
    }
     
    private void startAutoRefresh() {
        refreshTimer = new javax.swing.Timer(10000, e -> {
            if (this.isVisible() && this.isActive()) {
                controller.refreshTable(this.companyId);
            }
        });
        refreshTimer.start();
    }
  
    // Add this so the Controller can access your table
    public javax.swing.JTable getBookingTable() {
      return jTable1; 
   }

    public void showSuccess(String msg) { 
        JOptionPane.showMessageDialog(this, msg); 
    }

    public void showError(String msg) { 
        JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE); 
    }

    @Override
    public void dispose() {
        if (refreshTimer != null) refreshTimer.stop();
        super.dispose();
    }
     
   
         

        
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlogout = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        addVehicle = new javax.swing.JButton();
        jhistory = new javax.swing.JButton();
        llogo = new javax.swing.JLabel();
        llogout = new javax.swing.JLabel();
        lhistory = new javax.swing.JLabel();
        jreport = new javax.swing.JButton();
        lreport = new javax.swing.JLabel();
        jprofile = new javax.swing.JButton();
        view = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout_box_icon_206016 (1).png"))); // NOI18N
        jlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 37, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/notification-icon-illustration-template-stock-free-vector (1).jpg"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 40, 30));

        addVehicle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/addnewdocument_118445 (1).png"))); // NOI18N
        addVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVehicleActionPerformed(evt);
            }
        });
        getContentPane().add(addVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 134, 42, 36));

        jhistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/history-clock-button_icon-icons.com_72701 (2).png"))); // NOI18N
        jhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhistoryActionPerformed(evt);
            }
        });
        getContentPane().add(jhistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 20, 37, -1));

        llogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        getContentPane().add(llogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 110));

        llogout.setForeground(new java.awt.Color(255, 255, 255));
        llogout.setText("logout");
        getContentPane().add(llogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 50, 37, -1));

        lhistory.setForeground(new java.awt.Color(255, 255, 255));
        lhistory.setText("history");
        getContentPane().add(lhistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 50, 37, -1));

        jreport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/report_document_finance_business.png"))); // NOI18N
        jreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jreportActionPerformed(evt);
            }
        });
        getContentPane().add(jreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 20, 37, -1));

        lreport.setForeground(new java.awt.Color(255, 255, 255));
        lreport.setText("report");
        getContentPane().add(lreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 50, 37, -1));

        jprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jprofile.setText("profile");
        jprofile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jprofileMouseClicked(evt);
            }
        });
        jprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jprofileActionPerformed(evt);
            }
        });
        getContentPane().add(jprofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, 87, 65));

        view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/view_show_icon_124811 (1).png"))); // NOI18N
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        getContentPane().add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 182, 42, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("vehicle request");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 198, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("add");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 154, 37, -1));

        jButton3.setBackground(new java.awt.Color(51, 255, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Make Available");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 500, -1, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "vehicle Id", "Model", "Customer Id", "Booking ID", "Customer name", "Start date", "End date", "Price per day", "Total Price", "Payment Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(34);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 910, 300));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, 51, 32));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("Your Booked vehicles");
        jPanel1.add(jLabel5);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 380, 60));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("booking request");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 90, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/companyDashboard.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    private void jhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhistoryActionPerformed
      javax.swing.JFrame frame = new javax.swing.JFrame("Rental History - Company View");
    frame.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    
    // Use 'this.companyId' to match your class variable
    CompanyHistory historyPanel = new CompanyHistory(this.companyId); 
    
    frame.add(historyPanel);
    frame.pack();
    frame.setLocationRelativeTo(this);
    frame.setVisible(true);
    }//GEN-LAST:event_jhistoryActionPerformed
    private login loginpage;
    private void jlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogoutActionPerformed
        // TODO add your handling code here:
        if (loginpage == null) {
            loginpage = new login();
            loginpage.setSize(1366, 768);

        }
        if (loginpage.isVisible()) {
            loginpage.setVisible(false);
        } else {
            loginpage.setVisible(true);
            loginpage.toFront();
        }
        this.dispose();
    }//GEN-LAST:event_jlogoutActionPerformed
    private company_requestvehicle addVehicleFrame;
    private void addVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVehicleActionPerformed
        if (addVehicleFrame == null || !addVehicleFrame.isDisplayable()) {
            addVehicleFrame = new company_requestvehicle(this.companyId); 
            addVehicleFrame.setSize(920, 680);
        }

        if (addVehicleFrame.isVisible()) {
            addVehicleFrame.setVisible(false);
        } else {
            addVehicleFrame.setVisible(true);
            addVehicleFrame.toFront();
        }
    }//GEN-LAST:event_addVehicleActionPerformed

    private void jreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jreportActionPerformed
        EarningReport reportFrame = new EarningReport(this.companyId);
    reportFrame.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE); // Don't close whole app
    reportFrame.setVisible(true);
    }//GEN-LAST:event_jreportActionPerformed

    private void jprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jprofileActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jprofileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jprofileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jprofileMouseClicked
      

    }//GEN-LAST:event_jprofileMouseClicked
    private company_vehicleStatuslist viewwind;
    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
       // FIX: Pass 'this.companyId' so this window only shows 
        // vehicles belonging to THIS company.
        if (viewwind == null || !viewwind.isDisplayable()) {
            viewwind = new company_vehicleStatuslist(this.companyId); 
            viewwind.setSize(1000, 680);
        }
        
        if (viewwind.isVisible()) {
            viewwind.setVisible(false);
        } else {
            viewwind.setVisible(true);
            viewwind.toFront();
        }
    }//GEN-LAST:event_viewActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Pass the ID so the window knows WHICH company's requests to show
         company_bookingmanagementlist bookingWindow = new company_bookingmanagementlist(this.companyId);
        bookingWindow.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           int row = jTable1.getSelectedRow();
    if (row != -1) {
        int vId = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        int bId = Integer.parseInt(jTable1.getValueAt(row, 3).toString());
        controller.handleVehicleReturn(vId, bId, this.companyId);
    } else {
        showError("Please select a booking.");
    }
    }//GEN-LAST:event_jButton3ActionPerformed
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVehicle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jhistory;
    private javax.swing.JButton jlogout;
    private javax.swing.JButton jprofile;
    private javax.swing.JButton jreport;
    private javax.swing.JLabel lhistory;
    private javax.swing.JLabel llogo;
    private javax.swing.JLabel llogout;
    private javax.swing.JLabel lreport;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
