/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import UserController.company_vehiclestatusController;
import java.awt.Color;
import java.io.File;
import javax.swing.ImageIcon;
/**
 *
 * @author hp
 */
public class company_vehiclestatusdetail extends javax.swing.JPanel {

    private company_vehiclestatusController controller;

    public company_vehiclestatusdetail() {
        initComponents();
    }

    // Link the controller so deletion works
    public void setController(company_vehiclestatusController controller) {
        this.controller = controller;
    }

    public void setVehicleData(String brand, String model, String type, String color, String plate, String price, String status, String message, File frontImg, File sideImg) {
        jLabel9.setText(brand);
        jLabel10.setText(model);
        jLabel11.setText(type);
        jLabel12.setText(color);
        jLabel13.setText(plate);
        jLabel15.setText(price);
        
        String currentStatus = (status == null) ? "pending" : status.toLowerCase();
        jLabel2.setText(currentStatus.toUpperCase());

        // Status-based Styling
        if ("rejected".equals(currentStatus)) {
            jLabel2.setForeground(Color.RED);
            setRejectionUI(true, message);
        } else {
            Color successColor = ("accepted".equals(currentStatus) || "approved".equals(currentStatus)) 
                                 ? new Color(0, 153, 0) : new Color(255, 140, 0);
            jLabel2.setForeground(successColor);
            setRejectionUI(false, "");
        }

        // Image Handling
        loadLabelImage(frontImg, lblImage1, "No Front Image");
        loadLabelImage(sideImg, lblImage2, "No Side Image");
    }

    private void setRejectionUI(boolean visible, String msg) {
        jLabel14.setVisible(visible);
        jLabel17.setVisible(visible);
        jLabel18.setVisible(visible);
        jLabel18.setText(visible ? (msg == null || msg.isEmpty() ? "No reason provided." : msg) : "");
    }

    private void loadLabelImage(File file, javax.swing.JLabel label, String fallback) {
        if (file != null && file.exists()) {
            ImageIcon icon = new ImageIcon(file.getAbsolutePath());
            int w = label.getWidth() > 0 ? label.getWidth() : 400;
            int h = label.getHeight() > 0 ? label.getHeight() : 300;
            label.setIcon(new ImageIcon(icon.getImage().getScaledInstance(w, h, java.awt.Image.SCALE_SMOOTH)));
            label.setText("");
        } else {
            label.setIcon(null);
            label.setText(fallback);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage2 = new javax.swing.JLabel();
        lblImage1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 204, 255));

        lblImage2.setBackground(new java.awt.Color(255, 255, 255));
        lblImage2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblImage2.setForeground(new java.awt.Color(255, 255, 255));
        lblImage2.setText("                           insert Side photo  ");
        lblImage2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        lblImage2.setMaximumSize(new java.awt.Dimension(400, 300));
        lblImage2.setPreferredSize(new java.awt.Dimension(400, 300));

        lblImage1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblImage1.setForeground(new java.awt.Color(255, 255, 255));
        lblImage1.setText("         insert Front photo with number plate");
        lblImage1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        lblImage1.setMinimumSize(new java.awt.Dimension(400, 300));
        lblImage1.setPreferredSize(new java.awt.Dimension(400, 300));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Vehicle details");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(100, 10, 180, 30);

        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(140, 300, 220, 16);

        jLabel9.setText("jLabel2");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(150, 60, 220, 16);

        jLabel10.setText("jLabel2");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(150, 100, 220, 16);

        jLabel11.setText("jLabel2");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(150, 140, 220, 16);

        jLabel12.setText("jLabel2");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(150, 180, 220, 16);

        jLabel13.setText("jLabel2");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(150, 220, 220, 20);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("delete");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(150, 550, 80, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Brand               :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 60, 110, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("model              :  ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 100, 111, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Vehicle  Type  :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 140, 110, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Colour              :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 180, 110, 20);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Message          :");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(30, 350, 110, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Number Plate  :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 220, 110, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Price                 :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 260, 106, 20);

        jLabel15.setText("jLabel2");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(150, 260, 220, 16);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Status              :");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(30, 300, 110, 20);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("(if rejected)");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(30, 370, 70, 20);

        jLabel18.setText("jLabel18");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(140, 340, 240, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImage1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImage2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (controller != null) {
            controller.processDelete(jLabel13.getText().trim(), this);
        }
   
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblImage1;
    private javax.swing.JLabel lblImage2;
    // End of variables declaration//GEN-END:variables
}
