/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author prachisilwal
 */
public class Company_Manage_Account extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Company_Manage_Account.class.getName());

    /**
     * Creates new form Company_Manage_Account
     */
    public Company_Manage_Account() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        box = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        Company_Name = new javax.swing.JLabel();
        user_type_Full_Name = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        user_username_ = new javax.swing.JTextField();
        Contact = new javax.swing.JLabel();
        user_type_contact = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        user_type_Email = new javax.swing.JTextField();
        Address = new javax.swing.JLabel();
        user_type_Address = new javax.swing.JTextField();
        Update_Profile = new javax.swing.JButton();
        Change_Password = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        box.setBackground(new java.awt.Color(57, 174, 221));
        box.setLayout(null);

        Heading.setBackground(new java.awt.Color(43, 219, 43));
        Heading.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading.setText("My Account");
        Heading.setOpaque(true);
        box.add(Heading);
        Heading.setBounds(100, 20, 300, 50);

        Company_Name.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Company_Name.setText("Company Name      :");
        box.add(Company_Name);
        Company_Name.setBounds(20, 100, 140, 35);

        user_type_Full_Name.addActionListener(this::user_type_Full_NameActionPerformed);
        box.add(user_type_Full_Name);
        user_type_Full_Name.setBounds(170, 100, 310, 35);

        username.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        username.setText("username_              :");
        box.add(username);
        username.setBounds(20, 160, 140, 35);

        user_username_.addActionListener(this::user_username_ActionPerformed);
        box.add(user_username_);
        user_username_.setBounds(170, 160, 310, 35);

        Contact.setText("Contact no.               :");
        box.add(Contact);
        Contact.setBounds(20, 220, 140, 35);
        box.add(user_type_contact);
        user_type_contact.setBounds(170, 220, 310, 35);

        Email.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Email.setText("Email                       :");
        box.add(Email);
        Email.setBounds(20, 280, 140, 35);
        box.add(user_type_Email);
        user_type_Email.setBounds(170, 280, 310, 35);

        Address.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Address.setText("Address                   :");
        box.add(Address);
        Address.setBounds(20, 340, 140, 35);
        box.add(user_type_Address);
        user_type_Address.setBounds(170, 340, 310, 35);

        Update_Profile.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Update_Profile.setText("Update Profile");
        Update_Profile.addActionListener(this::Update_ProfileActionPerformed);
        box.add(Update_Profile);
        Update_Profile.setBounds(20, 410, 200, 40);

        Change_Password.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Change_Password.setText("Change Password");
        Change_Password.addActionListener(this::Change_PasswordActionPerformed);
        box.add(Change_Password);
        Change_Password.setBounds(280, 410, 200, 40);

        Cancel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(this::CancelActionPerformed);
        box.add(Cancel);
        Cancel.setBounds(170, 455, 150, 32);

        Logout.setBackground(new java.awt.Color(43, 219, 43));
        Logout.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(this::LogoutActionPerformed);
        box.add(Logout);
        Logout.setBounds(170, 490, 150, 40);

        getContentPane().add(box);
        box.setBounds(0, 0, 500, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_type_Full_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_type_Full_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_type_Full_NameActionPerformed

    private void user_username_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_username_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_username_ActionPerformed

    private void Update_ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_ProfileActionPerformed
        if (!editing) {
            // Switch to edit mode
            editing = true;
            Update_Profile.setText("Save");
            Cancel.setVisible(true);

            // Store original values for cancel
            originalFullName = user_type_Full_Name.getText();
            originalContact = user_type_contact.getText();
            originalEmail = user_type_Email.getText();
            originalAddress = user_type_Address.getText();

            user_type_Full_Name.setEditable(true);
            user_type_contact.setEditable(true);
            user_type_Email.setEditable(true);
            user_type_Address.setEditable(true);

            javax.swing.JOptionPane.showMessageDialog(this, "You can now edit your profile.");
            return;
        }

        // SAVE MODE
        String fullName = user_type_Full_Name.getText().trim();
        String contact = user_type_contact.getText().trim();
        String email = user_type_Email.getText().trim();
        String address = user_type_Address.getText().trim();
        String username = user_username_.getText().trim();

        if (fullName.isEmpty() || contact.isEmpty() || email.isEmpty() || address.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill all the fields.");
            return;
        }

        boolean updated = updateUserProfileInDB(username, fullName, contact, email, address);

        if (updated) {
            javax.swing.JOptionPane.showMessageDialog(this, "Profile updated successfully!");
            editing = false;
            Update_Profile.setText("Update Profile");
            Cancel.setVisible(false);

            user_type_Full_Name.setEditable(false);
            user_type_contact.setEditable(false);
            user_type_Email.setEditable(false);
            user_type_Address.setEditable(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to update profile. Please try again.");
        }
    }//GEN-LAST:event_Update_ProfileActionPerformed

    private void Change_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Change_PasswordActionPerformed
        User_ChangePassword dialog = new User_ChangePassword(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_Change_PasswordActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        user_type_Full_Name.setText(originalFullName);
        user_type_contact.setText(originalContact);
        user_type_Email.setText(originalEmail);
        user_type_Address.setText(originalAddress);

        editing = false;
        Update_Profile.setText("Update Profile");
        Cancel.setVisible(false);

        user_type_Full_Name.setEditable(false);
        user_type_contact.setEditable(false);
        user_type_Email.setEditable(false);
        user_type_Address.setEditable(false);
    }//GEN-LAST:event_CancelActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        this.dispose(); // Close current window
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Company_Manage_Account().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Change_Password;
    private javax.swing.JLabel Company_Name;
    private javax.swing.JLabel Contact;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Heading;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Update_Profile;
    private javax.swing.JPanel box;
    private javax.swing.JTextField user_type_Address;
    private javax.swing.JTextField user_type_Email;
    private javax.swing.JTextField user_type_Full_Name;
    private javax.swing.JTextField user_type_contact;
    private javax.swing.JTextField user_username_;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
