/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import UserController.company_vehiclestatusController;
import java.awt.Color;

/**
 *
 * @author hp
 */
public class company_vehicleinfoitems extends javax.swing.JPanel {
    private company_vehicleStatuslist mainFrame;
    private company_vehiclestatusController controller;

    public company_vehicleinfoitems() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));
    }

    // This connects the item to the main list and the controller
    public void setMainFrame(company_vehicleStatuslist frame) {
        this.mainFrame = frame;
        // Initialize controller with the actual frame so refresh works
        this.controller = new company_vehiclestatusController(frame);
    }

    public void setShortData(String name, String plate, String status) {
        model.setText(name);
        id.setText("Vec.ID :" + plate);
        stat.setText(status.toUpperCase());
        
        // Color coding
        if (status.equalsIgnoreCase("accepted") || status.equalsIgnoreCase("approved")) {
            stat.setForeground(new Color(0, 153, 0));
        } else if (status.equalsIgnoreCase("rejected")) {
            stat.setForeground(Color.RED);
        } else {
            stat.setForeground(new Color(204, 153, 0));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        model = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        stat = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        model.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        model.setText("Name");

        id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        id.setText("Vehicle.ID");

        stat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stat.setText("Status");

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("view");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(stat, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(model, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stat)
                    .addComponent(jButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          String plateNumber = id.getText().replace("Vec.ID :", "").trim();
        
        if (controller != null) {
            // "this" works here because JPanel is a child of java.awt.Component
            controller.handleViewDetails(plateNumber, this);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel model;
    private javax.swing.JLabel stat;
    // End of variables declaration//GEN-END:variables
}
