/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
/**
 *
 * @author hp
 */
public class company_bookingmanagementunit extends javax.swing.JPanel {

    // Internal data storage
    private int pId, bId, vId, days;
    private String name, address, phone, start, end;
    private double pricePerDay, total;
    private byte[] receiptImg, licenseImg;

    public company_bookingmanagementunit(int pId, int bId, int vId, String name, String address, String phone, 
                                 String start, String end, int days, double pricePerDay, double total, 
                                 byte[] receiptImg, byte[] licenseImg) {
        initComponents();
        
        // Data assignment
        this.pId = pId; 
        this.bId = bId; 
        this.vId = vId;
        this.name = name; 
        this.address = address; 
        this.phone = phone;
        this.start = start; 
        this.end = end; 
        this.days = days;
        this.pricePerDay = pricePerDay; 
        this.total = total;
        this.receiptImg = receiptImg; 
        this.licenseImg = licenseImg;

        // --- UI Mapping ---
        jLabel1.setText(name); // Customer Name
        jLabel3.setText("Booking ID: " + bId); // Changed to Booking ID for better tracking
        jLabel2.setText(String.format("Rs. %.2f", total)); 
        jLabel4.setText(days + " Days (" + start + " to " + end + ")"); 
         
        // --- UI Polish ---
        // Adds a thin line between units for a clean list look
        this.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        jButton1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButton1.setText("Review"); // Suggestive text for the admin
        
        // Set fixed size to prevent layout issues in the scrollable list
        this.setPreferredSize(new Dimension(875, 60)); // Increased slightly for breathing room
        this.setMaximumSize(new Dimension(1000, 60));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Name ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Price");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 130, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Vehicle Id");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 180, 30));

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("no of days");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
        company_bookingmanagementcard detailCard = new company_bookingmanagementcard(
            pId, bId, vId, name, address, phone, start, end, days, pricePerDay, total, receiptImg, licenseImg
        );

        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        javax.swing.JDialog dialog = new javax.swing.JDialog(
            parentWindow instanceof javax.swing.JFrame ? (javax.swing.JFrame)parentWindow : null, 
            "Booking Review - ID: " + bId, 
            true // Modal: Blocks interaction with parent until closed
        );
        
        // Add the card and setup the dialog
        dialog.getContentPane().add(detailCard);
        dialog.pack(); 
        dialog.setLocationRelativeTo(parentWindow); 
        dialog.setResizable(false);
        detailCard.setParentDialog(dialog); 
        dialog.setVisible(true); 
        if (parentWindow instanceof company_bookingmanagementlist) {
            ((company_bookingmanagementlist) parentWindow).loadBookings();

            parentWindow.revalidate();
            parentWindow.repaint();
        }
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error opening details: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
