/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import dao.paymentMethodDao;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import view.UserDashboard;
import dao.company_bookingmanagementDao;

/**
 *
 * @author hp
 */
public class company_bookingmanagementcard extends javax.swing.JPanel {
    private int paymentId, bookingId, vehicleId;
    private javax.swing.JDialog parentDialog;

      public company_bookingmanagementcard(int pId, int bId, int vId, String name, String address, String phone,
            String start, String end, int days, double pricePerDay, double total,
            byte[] receiptImg, byte[] licenseImg) {
        
        initComponents();
        this.paymentId = pId;
        this.bookingId = bId;
        this.vehicleId = vId;

        // 1. UI Mapping (Text Information)
        jLabel4.setText("Customer Name  : " + name);
        jLabel5.setText("Current Address : " + address);
        jLabel6.setText("Phone Number    : " + phone);
        jLabel7.setText("Start Date      : " + start);
        jLabel8.setText("End Date        : " + end);
        jLabel10.setText("No of Days     : " + days);
        jLabel9.setText(String.format("Price Per Day   : RS %.2f", pricePerDay));
        jLabel11.setText(String.format("Total Price     : RS %.2f", total));

        // 2. Display Images
        // jLabel3 = Receipt, jLabel2 = License
        displayImage(jLabel3, receiptImg, "No Receipt Uploaded");
        displayImage(jLabel2, licenseImg, "No License Uploaded");

        // 3. Finalize UI Layout
        this.revalidate();
        this.repaint();
    }

    private void displayImage(javax.swing.JLabel label, byte[] data, String emptyText) {
        if (data != null && data.length > 0) {
            label.setText("");
            
            // Use label's current size if available, otherwise use default design size
            int targetWidth = label.getWidth() > 0 ? label.getWidth() : 400;
            int targetHeight = label.getHeight() > 0 ? label.getHeight() : 280;
            
            label.setIcon(formatImage(data, targetWidth, targetHeight));
            label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        } else {
            label.setIcon(null);
            label.setText("<html><body style='text-align: center; color: gray;'>" + emptyText + "</body></html>");
            label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        }
    }

    private javax.swing.ImageIcon formatImage(byte[] img, int w, int h) {
        try {
            if (img == null || img.length == 0) return null;

            javax.swing.ImageIcon imageIcon = new javax.swing.ImageIcon(img);
            java.awt.Image image = imageIcon.getImage();

            // Calculate scaling that fits the box without stretching (Keep Aspect Ratio)
            int originalWidth = imageIcon.getIconWidth();
            int originalHeight = imageIcon.getIconHeight();

            double widthRatio = (double) w / originalWidth;
            double heightRatio = (double) h / originalHeight;
            double scaleFactor = Math.min(widthRatio, heightRatio);

            int scaledWidth = (int) (originalWidth * scaleFactor);
            int scaledHeight = (int) (originalHeight * scaleFactor);

            java.awt.Image scaledImage = image.getScaledInstance(scaledWidth, scaledHeight, java.awt.Image.SCALE_SMOOTH);
            return new javax.swing.ImageIcon(scaledImage);
        } catch (Exception e) {
            System.err.println("Image Formatting Error: " + e.getMessage());
            return null;
        }
    }

    public void setParentDialog(javax.swing.JDialog dialog) {
        this.parentDialog = dialog;
    }
    
    // Logic for the Accept/Reject buttons should call this to close the popup
    private void closeParent() {
        if (parentDialog != null) {
            parentDialog.dispose();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 204, 255));
        setMaximumSize(new java.awt.Dimension(920, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Booking Request");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Customer Name  :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Current Address  :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Phone Number    :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Start Date             :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("End Date               :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Price Per Day        :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("No of Days            :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Total Price            :");

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Accept");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Reject");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(19, 19, 19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("                                Licence (if self drive)");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                          Payment Receipt (if online)");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, 
        "Accept this booking? This will finalize the payment and reserve the vehicle.", 
        "Confirm Acceptance", 
        JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        dao.company_bookingmanagementDao mgtDao = new dao.company_bookingmanagementDao();
        
        // We use specific statuses that match our application logic
        boolean success = mgtDao.updateFullBookingStatus(
            paymentId, 
            bookingId, 
            vehicleId, 
            "paid",      // Update Payment to paid
            "Approved",  // Update Booking to Approved
            "booked"     // Keep/Set Vehicle as booked
        );

        if (success) { 
            JOptionPane.showMessageDialog(this, "Booking Approved successfully!");
            closeDialog(); // This triggers the refresh in company_bookingmanagementlist.java
        } else {
            JOptionPane.showMessageDialog(this, "System Error: Transaction failed.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     // 1. Confirm Rejection with a Warning icon
    int confirm = JOptionPane.showConfirmDialog(this, """
                                                      Reject this booking?
                                                      
                                                      This will:
                                                      - Set Payment as 'failed'
                                                      - Set Booking as 'Rejected'
                                                      - Make the Vehicle 'available' for others.""", 
        "Confirm Rejection", 
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE);

    if (confirm == JOptionPane.YES_OPTION) {
        // Initialize the transactional DAO
        dao.company_bookingmanagementDao mgtDao = new dao.company_bookingmanagementDao();
        
        // Log the action for debugging (Helpful if database constraints fail)
        System.out.println("Processing Rejection - PayID: " + paymentId + ", BookID: " + bookingId + ", VehID: " + vehicleId);
        
        // Execute the multi-table update
        // Note: Using 'available' for the vehicle ensures it reappears in search results for other users
        boolean success = mgtDao.updateFullBookingStatus(
            paymentId, 
            bookingId, 
            vehicleId, 
            "failed",    // payments.status
            "Rejected",  // bookings.status
            "available"  // vehicleDetails.availability_status
        );

        if (success) {
            JOptionPane.showMessageDialog(this, 
                "Booking Rejected successfully.\nThe vehicle has been released back to the fleet.", 
                "Rejection Successful", 
                JOptionPane.INFORMATION_MESSAGE);
            
            // This method closes the JDialog and calls loadBookings() on the main dashboard
            closeDialog(); 
        } else {
            JOptionPane.showMessageDialog(this, 
                "Database Error: Could not process rejection.\nPlease check your connection or system logs.", 
                "Transaction Failed", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButton2ActionPerformed
      private void closeDialog() {
    // 1. Find the window containing this card (the Popup)
    java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
    
    if (win != null) {
        // 2. Identify the 'Owner' of this popup (the main Booking Management screen)
        java.awt.Window owner = win.getOwner();
        
        // 3. Close the popup first
        win.dispose();
        
        // 4. Trigger the refresh on the main screen so the list updates
        if (owner instanceof company_bookingmanagementlist) {
            ((company_bookingmanagementlist) owner).loadBookings();
        }
    }
}
  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
