/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import UserController.companyRegisterController;
import util.RegistrationResult;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.io.File;
import java.net.URL;

/**
 *
 * @author prachisilwal
 */
public class Company_Registration_Panel extends javax.swing.JPanel {
     private companyRegisterController controller = new companyRegisterController();
     private String qrPath = "";
    /**
     * Creates new form Company_Registration
     */
    public Company_Registration_Panel() {
    initComponents();
    loadImagesSafely();
    
    // UI Initial State
    Company.setEnabled(false); 
    Seeker.setEnabled(true);
    underline_company.setBounds(40, 120, 160, 4);
    
   
}

    private void loadImagesSafely() {
        try {
            URL logoUrl = getClass().getResource("/images/Sadhan Logo.jpeg");
            URL bgUrl = getClass().getResource("/images/bg picture (1).jpeg");
            if (logoUrl != null) logo.setIcon(new ImageIcon(logoUrl));
            if (bgUrl != null) background.setIcon(new ImageIcon(bgUrl));
        } catch (Exception e) {
            System.err.println("Error loading images: " + e.getMessage());
        }
    }
    private void uploadQRActionPerformed() {
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image files", "jpg", "png", "jpeg"));
    
    int result = fileChooser.showOpenDialog(this);
    
    // Only proceed if the user actually clicked "Open"
    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();
        qrPath = selectedFile.getAbsolutePath();
        
        // Scaling logic...
        int width = (QR.getWidth() > 0) ? QR.getWidth() : 120;
        int height = (QR.getHeight() > 0) ? QR.getHeight() : 90;

        ImageIcon icon = new ImageIcon(new ImageIcon(qrPath).getImage()
            .getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH));
        
        QR.setText("");
        QR.setIcon(icon);
    } 
    // If result == JFileChooser.CANCEL_OPTION, the method simply ends, which is what we want!

}

      private void clearFields() {
        user_type_Company_Name.setText("");
        user_username_.setText("");
        user_type_Contact.setText("");
        user_type_Email.setText("");
        user_type_Address.setText("");
        user_type_Password.setText("");
        user_type_Reenter_Password.setText("");
        user_type_Security_Question.setText("");
        QR.setIcon(null);
        QR.setText("QR Preview");
        qrPath = "";
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        box = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        underline_company = new javax.swing.JPanel();
        Company = new javax.swing.JButton();
        Seeker = new javax.swing.JButton();
        Company_Name = new javax.swing.JLabel();
        user_type_Company_Name = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        user_username_ = new javax.swing.JTextField();
        Contact = new javax.swing.JLabel();
        user_type_Contact = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        user_type_Email = new javax.swing.JTextField();
        Address = new javax.swing.JLabel();
        user_type_Address = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        pass_checkbox = new javax.swing.JCheckBox();
        user_type_Password = new javax.swing.JPasswordField();
        Reenter_password = new javax.swing.JLabel();
        reenter_checkbox = new javax.swing.JCheckBox();
        user_type_Reenter_Password = new javax.swing.JPasswordField();
        Security_Question = new javax.swing.JLabel();
        user_type_Security_Question = new javax.swing.JTextField();
        QR = new javax.swing.JLabel();
        Register = new javax.swing.JButton();
        Login_here = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        box.setBackground(new java.awt.Color(57, 174, 221));
        box.setLayout(null);

        Heading.setBackground(new java.awt.Color(43, 219, 43));
        Heading.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading.setText("RENT YOUR ADVENTURE");
        Heading.setOpaque(true);
        box.add(Heading);
        Heading.setBounds(80, 10, 400, 50);

        underline_company.setBackground(new java.awt.Color(0, 0, 0));
        underline_company.setMinimumSize(new java.awt.Dimension(10, 3));
        box.add(underline_company);
        underline_company.setBounds(40, 120, 160, 4);

        Company.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        Company.setText("Company");
        Company.setIconTextGap(5);
        Company.addActionListener(this::CompanyActionPerformed);
        box.add(Company);
        Company.setBounds(40, 80, 160, 45);

        Seeker.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        Seeker.setText("Seeker");
        Seeker.setIconTextGap(5);
        Seeker.addActionListener(this::SeekerActionPerformed);
        box.add(Seeker);
        Seeker.setBounds(340, 80, 160, 45);

        Company_Name.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Company_Name.setText("Company Name       :");
        box.add(Company_Name);
        Company_Name.setBounds(30, 140, 140, 35);

        user_type_Company_Name.addActionListener(this::user_type_Company_NameActionPerformed);
        box.add(user_type_Company_Name);
        user_type_Company_Name.setBounds(180, 140, 340, 35);

        username.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        username.setText("username_              :");
        box.add(username);
        username.setBounds(30, 200, 140, 35);
        box.add(user_username_);
        user_username_.setBounds(180, 200, 340, 35);

        Contact.setText("Contact no.               :");
        box.add(Contact);
        Contact.setBounds(30, 260, 140, 35);
        box.add(user_type_Contact);
        user_type_Contact.setBounds(180, 260, 340, 35);

        Email.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Email.setText("Email                       :");
        box.add(Email);
        Email.setBounds(30, 320, 140, 35);
        box.add(user_type_Email);
        user_type_Email.setBounds(180, 320, 340, 35);

        Address.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Address.setText("Address                   :");
        box.add(Address);
        Address.setBounds(30, 380, 140, 35);
        box.add(user_type_Address);
        user_type_Address.setBounds(180, 380, 340, 35);

        Password.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Password.setText("Password                :");
        box.add(Password);
        Password.setBounds(30, 440, 140, 35);

        pass_checkbox.addActionListener(this::pass_checkboxActionPerformed);
        box.add(pass_checkbox);
        pass_checkbox.setBounds(490, 440, 19, 35);
        box.add(user_type_Password);
        user_type_Password.setBounds(180, 440, 340, 35);

        Reenter_password.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Reenter_password.setText("Re-enter password  :");
        box.add(Reenter_password);
        Reenter_password.setBounds(30, 500, 140, 35);

        reenter_checkbox.addActionListener(this::reenter_checkboxActionPerformed);
        box.add(reenter_checkbox);
        reenter_checkbox.setBounds(490, 500, 19, 35);
        box.add(user_type_Reenter_Password);
        user_type_Reenter_Password.setBounds(180, 500, 340, 35);

        Security_Question.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Security_Question.setText("Security Question    :   What's your favourite place ?");
        box.add(Security_Question);
        Security_Question.setBounds(30, 550, 340, 35);

        user_type_Security_Question.addActionListener(this::user_type_Security_QuestionActionPerformed);
        box.add(user_type_Security_Question);
        user_type_Security_Question.setBounds(180, 580, 340, 35);

        QR.setText("QR preview");
        box.add(QR);
        QR.setBounds(20, 630, 120, 90);

        Register.setBackground(new java.awt.Color(43, 219, 43));
        Register.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        Register.setText("Register");
        Register.addActionListener(this::RegisterActionPerformed);
        box.add(Register);
        Register.setBounds(250, 630, 110, 30);

        Login_here.setText("already have an account ?, login here !");
        Login_here.addActionListener(this::Login_hereActionPerformed);
        box.add(Login_here);
        Login_here.setBounds(180, 680, 250, 30);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Upload your QR");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        box.add(jButton1);
        jButton1.setBounds(20, 593, 130, 20);

        add(box, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 550, 740));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 110));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg picture (1).jpeg"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));
    }// </editor-fold>//GEN-END:initComponents

    private void user_type_Security_QuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_type_Security_QuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_type_Security_QuestionActionPerformed

    private void reenter_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reenter_checkboxActionPerformed
        if (reenter_checkbox.isSelected()) {
            user_type_Reenter_Password.setEchoChar((char) 0);
        } else {
            user_type_Reenter_Password.setEchoChar('•');
        }
    }//GEN-LAST:event_reenter_checkboxActionPerformed

    private void pass_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_checkboxActionPerformed
        if (pass_checkbox.isSelected()) {
            user_type_Password.setEchoChar((char) 0);
        } else {
            user_type_Password.setEchoChar('•');
        }
    }//GEN-LAST:event_pass_checkboxActionPerformed

    private void user_type_Company_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_type_Company_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_type_Company_NameActionPerformed

    private void SeekerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeekerActionPerformed
    java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
    if (parentWindow instanceof RegistrationFrame) {
        RegistrationFrame frame = (RegistrationFrame) parentWindow;
        // Switches to Seeker view
        frame.showCard("seeker"); 
        clearFields();
    }

    }//GEN-LAST:event_SeekerActionPerformed

    private void CompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyActionPerformed
         
    }//GEN-LAST:event_CompanyActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
         // 1. Collect Data from UI
        String companyName = user_type_Company_Name.getText();
        String usernameText = user_username_.getText();
        String contact = user_type_Contact.getText();
        String email = user_type_Email.getText();
        String address = user_type_Address.getText();
        String password = new String(user_type_Password.getPassword());
        String confirmPassword = new String(user_type_Reenter_Password.getPassword());
        String securityQuestion = user_type_Security_Question.getText();

        // 2. Validation
        if (companyName.isEmpty() || usernameText.isEmpty() || email.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all required fields.");
            return;
        }

        // 3. Call Controller for Registration
        RegistrationResult result = controller.registerCompany(
            companyName,
            usernameText,
            contact,
            email,
            address,
            password,
            confirmPassword,
            securityQuestion,
            qrPath // Pass the class-level qrPath variable here
    );
    if (result.isSuccess()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Account Created Successfully!");
    
    clearFields();

    // 1. Open the new Login window
    // Replace 'Login_Frame' with your actual Login class name
    

    //  Close the current Registration window
    java.awt.Window currentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
    if (currentWindow != null) {
        currentWindow.dispose();
    }
}
   
    }//GEN-LAST:event_RegisterActionPerformed

    private void Login_hereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_hereActionPerformed
     // 1. Open the new standalone window
    
    //  Immediately close the current Registration window
    java.awt.Window currentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
    if (currentWindow != null) {
        currentWindow.dispose();
    }
    }//GEN-LAST:event_Login_hereActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               uploadQRActionPerformed();       
    }//GEN-LAST:event_jButton1ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JButton Company;
    private javax.swing.JLabel Company_Name;
    private javax.swing.JLabel Contact;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Heading;
    private javax.swing.JButton Login_here;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel QR;
    private javax.swing.JLabel Reenter_password;
    private javax.swing.JButton Register;
    private javax.swing.JLabel Security_Question;
    private javax.swing.JButton Seeker;
    private javax.swing.JLabel background;
    private javax.swing.JPanel box;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel logo;
    private javax.swing.JCheckBox pass_checkbox;
    private javax.swing.JCheckBox reenter_checkbox;
    private javax.swing.JPanel underline_company;
    private javax.swing.JTextField user_type_Address;
    private javax.swing.JTextField user_type_Company_Name;
    private javax.swing.JTextField user_type_Contact;
    private javax.swing.JTextField user_type_Email;
    private javax.swing.JPasswordField user_type_Password;
    private javax.swing.JPasswordField user_type_Reenter_Password;
    private javax.swing.JTextField user_type_Security_Question;
    private javax.swing.JTextField user_username_;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
