/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.*;


/**
 *
 * @author hp
 */
public class companyDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(companyDashboard.class.getName());

    /**
     * Creates new form companyDashboard
     */

    public companyDashboard() {
        
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlogout = new javax.swing.JButton();
        addVehicle = new javax.swing.JButton();
        jhistory = new javax.swing.JButton();
        llogo = new javax.swing.JLabel();
        llogout = new javax.swing.JLabel();
        lhistory = new javax.swing.JLabel();
        jreport = new javax.swing.JButton();
        lreport = new javax.swing.JLabel();
        jprofile = new javax.swing.JButton();
        view = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout_box_icon_206016 (1).png"))); // NOI18N
        jlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 37, -1));

        addVehicle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/addnewdocument_118445 (1).png"))); // NOI18N
        addVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVehicleActionPerformed(evt);
            }
        });
        getContentPane().add(addVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 134, 42, 36));

        jhistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/history-clock-button_icon-icons.com_72701 (2).png"))); // NOI18N
        jhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhistoryActionPerformed(evt);
            }
        });
        getContentPane().add(jhistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 20, 37, -1));

        llogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        getContentPane().add(llogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 110));

        llogout.setForeground(new java.awt.Color(255, 255, 255));
        llogout.setText("logout");
        getContentPane().add(llogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 50, 37, -1));

        lhistory.setForeground(new java.awt.Color(255, 255, 255));
        lhistory.setText("history");
        getContentPane().add(lhistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 50, 37, -1));

        jreport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/report_document_finance_business.png"))); // NOI18N
        jreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jreportActionPerformed(evt);
            }
        });
        getContentPane().add(jreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 20, 37, -1));

        lreport.setForeground(new java.awt.Color(255, 255, 255));
        lreport.setText("report");
        getContentPane().add(lreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 50, 37, -1));

        jprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jprofile.setText("profile");
        jprofile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jprofileMouseClicked(evt);
            }
        });
        jprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jprofileActionPerformed(evt);
            }
        });
        getContentPane().add(jprofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, 87, 65));

        view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/view_show_icon_124811 (1).png"))); // NOI18N
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        getContentPane().add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 182, 42, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("view");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 198, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("add");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 154, 37, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, 51, 32));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/companyDashboard.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
       private history historypage;
    private void jhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhistoryActionPerformed
        // TODO add your handling code here:
          if (adWindow==null){
            historypage =new history();
            historypage.setSize(920, 680);
            
        }
        if (historypage.isVisible()){
            historypage.setVisible(false);
        }else{
            historypage.setVisible(true);
            historypage.toFront();
        }
    }//GEN-LAST:event_jhistoryActionPerformed
     private login loginpage;
    private void jlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogoutActionPerformed
        // TODO add your handling code here:
         if (loginpage==null){
            loginpage =new login();
            loginpage.setSize(1366, 768);
            
        }
        if (loginpage.isVisible()){
            loginpage.setVisible(false);
        }else{
            loginpage.setVisible(true);
            loginpage.toFront();
        }
        this.dispose();
    }//GEN-LAST:event_jlogoutActionPerformed
    private requestVehicleApproval addVehicleFrame;
    private void addVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVehicleActionPerformed
        // TODO add your handling code here:
         if (addVehicleFrame == null || !addVehicleFrame.isDisplayable()) {
          addVehicleFrame = new requestVehicleApproval ();
          addVehicleFrame.setSize(920, 650);
          
        }
        
        if (addVehicleFrame.isVisible()){
            addVehicleFrame.setVisible(false);
        }else{
            addVehicleFrame.setVisible(true);
            addVehicleFrame.toFront();
        }
         
        
       
        
    }//GEN-LAST:event_addVehicleActionPerformed
      private report Reportpage;
    private void jreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jreportActionPerformed
        // TODO add your handling code here:
            if (Reportpage==null){
           Reportpage =new report();
            Reportpage.setSize(920, 650);
            
        }
        if (Reportpage.isVisible()){
            Reportpage.setVisible(false);
        }else{
            Reportpage.setVisible(true);
            Reportpage.toFront();
        }
    }//GEN-LAST:event_jreportActionPerformed

    private void jprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jprofileActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jprofileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    private aboutProfile adWindow;
    private void jprofileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jprofileMouseClicked
        // TODO add your handling code here:
        if (adWindow==null){
            adWindow =new aboutProfile();
            adWindow.setSize(500, 550);
            
        }
        if (adWindow.isVisible()){
            adWindow.setVisible(false);
        }else{
            adWindow.setVisible(true);
            adWindow.toFront();
        }
        
        
    }//GEN-LAST:event_jprofileMouseClicked
    private view viewwind;
    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
         if (viewwind==null){
            viewwind =new view();
            viewwind.setSize(500, 550);
            
        }
        if (viewwind.isVisible()){
            viewwind.setVisible(false);
        }else{
            viewwind.setVisible(true);
            viewwind.toFront();
        }
        
    }//GEN-LAST:event_viewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new companyDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVehicle;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jhistory;
    private javax.swing.JButton jlogout;
    private javax.swing.JButton jprofile;
    private javax.swing.JButton jreport;
    private javax.swing.JLabel lhistory;
    private javax.swing.JLabel llogo;
    private javax.swing.JLabel llogout;
    private javax.swing.JLabel lreport;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
