/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import sadhan.*;

/**
 *
 * @author Aavash
 */
public class login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        LoginBTN.setEnabled(false);
    }
    
    public void clear(){
        Username.setText("");
        Password.setText("");
        LoginBTN.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Welcome = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        LoginBTN = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        forgotpassword = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        Show_password = new javax.swing.JLabel();
        show_password_button = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Welcome.setBackground(new java.awt.Color(0, 204, 255));
        Welcome.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Welcome.setText("Welcome!");
        getContentPane().add(Welcome);
        Welcome.setBounds(570, 160, 222, 48);

        Username.setText("username");
        getContentPane().add(Username);
        Username.setBounds(530, 270, 269, 35);

        register.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        register.setText("Don't have an account? register here!");
        getContentPane().add(register);
        register.setBounds(530, 520, 300, 27);

        Password.setText("enterpassword");
        Password.addActionListener(this::PasswordActionPerformed);
        getContentPane().add(Password);
        Password.setBounds(530, 340, 269, 35);

        LoginBTN.setBackground(new java.awt.Color(51, 255, 0));
        LoginBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LoginBTN.setText("Login");
        LoginBTN.addActionListener(this::LoginBTNBTNActionPerformed);
        getContentPane().add(LoginBTN);
        LoginBTN.setBounds(620, 470, 100, 32);

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/back_icon (1).png"))); // NOI18N
        Back.addActionListener(this::BackActionPerformed);
        getContentPane().add(Back);
        Back.setBounds(880, 540, 30, 30);

        forgotpassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        forgotpassword.setForeground(new java.awt.Color(51, 51, 255));
        forgotpassword.setText("forgot password?");
        getContentPane().add(forgotpassword);
        forgotpassword.setBounds(780, 430, 130, 20);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/logo.png"))); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(60, 40, 111, 120);

        Show_password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Show_password.setForeground(new java.awt.Color(51, 51, 255));
        Show_password.setText("Show Password");
        getContentPane().add(Show_password);
        Show_password.setBounds(780, 400, 120, 20);
        getContentPane().add(show_password_button);
        show_password_button.setBounds(760, 400, 18, 16);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/login_background (1).png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1290, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you want to exit the login page","Select",JOptionPane.YES_NO_OPTION);
        if (a==0) {
            System.exit(0);
        }
    }//GEN-LAST:event_BackActionPerformed

    private void LoginBTNBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBTNBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginBTNBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton LoginBTN;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel Show_password;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel Welcome;
    private javax.swing.JLabel background;
    private javax.swing.JLabel forgotpassword;
    private javax.swing.JLabel logo;
    private javax.swing.JButton register;
    private javax.swing.JButton show_password_button;
    // End of variables declaration//GEN-END:variables


    public void addLoginListener(ActionListener listener) {
        LoginBTN.addActionListener(listener);
    }

    public javax.swing.JPasswordField getPasswordField() {
        return Password;
    }

    public javax.swing.JTextField getUsernameField() {
        return Username;
    }


}
