/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import database.MySqlConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import database.MySqlConnection;
import javax.swing.JFrame;
/**
 *
 * @author hp
 */
 public class User_vehiclebooknow extends javax.swing.JPanel {

    private javax.swing.JFrame parentFrame;
    private int loggedInUserId;
    private int currentVehicleId; 
    private int currentCompanyId; // Track company ID for the booking record

    public User_vehiclebooknow() {
        initComponents();
    }

    public void setLoggedInUserId(int userId) {
    this.loggedInUserId = userId;
    }

    public void setParentFrame(javax.swing.JFrame frame) {
    this.parentFrame = frame;
     }

    // UPDATED: Now matches the 10-parameter signature from vehicleitems
    public void setVehicleData(int vId, int cId, String brand, String model, String type, String color, String plate, String price, java.io.File frontImg, java.io.File sideImg) {
        this.currentVehicleId = vId;
        this.currentCompanyId = cId;
        
        // Update UI Labels
        jLabel15.setText(String.valueOf(vId)); 
        jLabel7.setText(String.valueOf(cId)); 
        jLabel6.setText(brand);                
        jLabel9.setText(model);               
        jLabel5.setText(type);               
        jLabel4.setText(color);                
        jLabel3.setText(plate);              
        jLabel2.setText(price);             

        // Handle Images
        updateImage(frontImg, lblImage1, "Front Image");
        updateImage(sideImg, lblImage2, "Side Image");
    }

    private void updateImage(java.io.File file, javax.swing.JLabel label, String placeholder) {
        label.setIcon(null);
        if (file != null && file.exists()) {
            displayImage(file, label);
        } else {
            label.setText(placeholder + " Not Available");
        }
    }

    private void displayImage(java.io.File file, javax.swing.JLabel label) {
        try {
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(file.getAbsolutePath());
            // Fixed scaling logic to avoid 0-width errors
            int w = label.getWidth() > 0 ? label.getWidth() : 400;
            int h = label.getHeight() > 0 ? label.getHeight() : 300;
            
            java.awt.Image img = icon.getImage().getScaledInstance(w, h, java.awt.Image.SCALE_SMOOTH);
            label.setIcon(new javax.swing.ImageIcon(img));
            label.setText(""); 
        } catch (Exception e) {
            label.setText("Scale Error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImage2 = new javax.swing.JLabel();
        lblImage1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        b = new javax.swing.JLabel();
        cid = new javax.swing.JLabel();
        t = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        p = new javax.swing.JLabel();
        ppd = new javax.swing.JLabel();
        m = new javax.swing.JLabel();
        vid = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(920, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(950, 650));
        jPanel1.setMinimumSize(new java.awt.Dimension(950, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 680));

        lblImage2.setBackground(new java.awt.Color(255, 255, 255));
        lblImage2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblImage2.setForeground(new java.awt.Color(255, 255, 255));
        lblImage2.setText("                           insert Side photo  ");
        lblImage2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        lblImage2.setMaximumSize(new java.awt.Dimension(400, 300));
        lblImage2.setPreferredSize(new java.awt.Dimension(400, 300));

        lblImage1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblImage1.setForeground(new java.awt.Color(255, 255, 255));
        lblImage1.setText("         insert Front photo with number plate");
        lblImage1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        lblImage1.setMinimumSize(new java.awt.Dimension(400, 300));
        lblImage1.setPreferredSize(new java.awt.Dimension(400, 300));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Vehicle details");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(110, 10, 180, 30);

        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(140, 340, 220, 16);

        jLabel15.setText("jLabel2");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(140, 70, 220, 16);

        jLabel7.setText("jLabel2");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(140, 110, 220, 16);

        jLabel6.setText("jLabel2");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(140, 150, 220, 16);

        jLabel9.setText("jLabel5");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(140, 180, 220, 16);

        jLabel5.setText("jLabel2");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(140, 220, 220, 16);

        jButton2.setBackground(new java.awt.Color(102, 255, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Book Now");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(150, 440, 80, 30);

        b.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b.setText("Brand               :");
        jPanel2.add(b);
        b.setBounds(30, 150, 110, 16);

        cid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cid.setText("Company Id    :  ");
        jPanel2.add(cid);
        cid.setBounds(30, 110, 110, 20);

        t.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        t.setText("Vehicle  Type   :");
        jPanel2.add(t);
        t.setBounds(30, 220, 110, 20);

        c.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        c.setText("Colour              :");
        jPanel2.add(c);
        c.setBounds(30, 260, 110, 20);

        p.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        p.setText("Number Plate  :");
        jPanel2.add(p);
        p.setBounds(30, 300, 110, 20);

        ppd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ppd.setText("Price per day   :");
        jPanel2.add(ppd);
        ppd.setBounds(30, 340, 110, 20);

        m.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        m.setText("model               :  ");
        jPanel2.add(m);
        m.setBounds(30, 180, 115, 20);

        vid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vid.setText("Vehicle Id        :  ");
        jPanel2.add(vid);
        vid.setBounds(30, 70, 115, 20);

        jLabel4.setText("jLabel2");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(140, 260, 220, 16);

        jLabel3.setText("jLabel2");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(140, 300, 220, 16);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImage1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImage2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 930, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          UserController.booknowController controller = new UserController.booknowController();
    controller.handleBookingRequest(this.loggedInUserId, this.currentVehicleId, this.currentCompanyId, this);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b;
    private javax.swing.JLabel c;
    private javax.swing.JLabel cid;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblImage1;
    private javax.swing.JLabel lblImage2;
    private javax.swing.JLabel m;
    private javax.swing.JLabel p;
    private javax.swing.JLabel ppd;
    private javax.swing.JLabel t;
    private javax.swing.JLabel vid;
    // End of variables declaration//GEN-END:variables
}
