/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author prachisilwal
 */
public class User_Registration extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(User_Registration.class.getName());

    /**
     * Creates new form User_Registration
     */
    public User_Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heading = new javax.swing.JTextField();
        Company = new javax.swing.JLabel();
        Seeker = new javax.swing.JLabel();
        Full_Name = new javax.swing.JTextField();
        username_ = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        re_enter_password = new javax.swing.JTextField();
        box = new javax.swing.JTextField();
        logo = new javax.swing.JLabel();
        login_here = new javax.swing.JLabel();
        Register = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        heading.setBackground(new java.awt.Color(43, 219, 43));
        heading.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        heading.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        heading.setText("RENT YOUR ADVENTURE");
        heading.addActionListener(this::headingActionPerformed);
        getContentPane().add(heading);
        heading.setBounds(110, 140, 330, 50);

        Company.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Company.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Company.setText("Company");
        getContentPane().add(Company);
        Company.setBounds(130, 200, 90, 30);

        Seeker.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Seeker.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Seeker.setText("Seeker");
        getContentPane().add(Seeker);
        Seeker.setBounds(350, 200, 70, 30);

        Full_Name.setText("Full Name");
        Full_Name.addActionListener(this::Full_NameActionPerformed);
        getContentPane().add(Full_Name);
        Full_Name.setBounds(110, 250, 330, 30);

        username_.setText("username_");
        getContentPane().add(username_);
        username_.setBounds(110, 300, 330, 30);

        contact.setText("Contact no.");
        getContentPane().add(contact);
        contact.setBounds(110, 350, 330, 30);

        Email.setText("Email");
        getContentPane().add(Email);
        Email.setBounds(110, 400, 330, 30);

        Password.setText("Password");
        getContentPane().add(Password);
        Password.setBounds(110, 500, 330, 30);

        Address.setText("Address");
        getContentPane().add(Address);
        Address.setBounds(110, 450, 330, 30);

        re_enter_password.setText("Re-enter password");
        getContentPane().add(re_enter_password);
        re_enter_password.setBounds(110, 550, 330, 30);

        box.setBackground(new java.awt.Color(57, 174, 221));
        box.addActionListener(this::boxActionPerformed);
        getContentPane().add(box);
        box.setBounds(70, 120, 410, 480);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AAADBFF1-8C5B-4E31-9A82-B079FE0C740A_4_5005_c.jpeg"))); // NOI18N
        logo.setText("jLabel1");
        getContentPane().add(logo);
        logo.setBounds(-10, 10, 120, 110);

        login_here.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        login_here.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_here.setText("Already have account? Login here.");
        getContentPane().add(login_here);
        login_here.setBounds(160, 668, 230, 30);

        Register.setBackground(new java.awt.Color(0, 191, 239));
        Register.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        Register.setText("Register");
        getContentPane().add(Register);
        Register.setBounds(200, 620, 140, 36);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/59350E3D-3276-4ADE-BF78-1E029AD2BAF8.png"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_headingActionPerformed

    private void Full_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Full_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Full_NameActionPerformed

    private void boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new User_Registration().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JLabel Company;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Full_Name;
    private javax.swing.JTextField Password;
    private javax.swing.JButton Register;
    private javax.swing.JLabel Seeker;
    private javax.swing.JLabel background;
    private javax.swing.JTextField box;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField heading;
    private javax.swing.JLabel login_here;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField re_enter_password;
    private javax.swing.JTextField username_;
    // End of variables declaration//GEN-END:variables
}
