/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import UserController.UserAccountController;
import javax.swing.JOptionPane;
import model.UserAccount;

/**
 *
 * @author prachisilwal
 */
public class User_Manage_Account extends javax.swing.JFrame {
    
    private final UserAccountController controller = new UserAccountController();
    private String loggedInUsername;
    private boolean editing = false;
    
    private String originalFullName, originalContact, originalEmail, originalAddress;

    public User_Manage_Account(String username) {
        initComponents();
        loggedInUsername = username;

        user_username_.setText(loggedInUsername);
        user_username_.setEditable(false);

        setEditable(false);
        Cancel.setVisible(false);

        loadUserData();
        setVisible(true);
    }
    
    private void loadUserData() {
            UserAccount user = controller.load(loggedInUsername);
            if (user != null) {
            user_type_Full_Name.setText(user.getFullName());
            user_type_contact.setText(user.getContact());
            user_type_Email.setText(user.getEmail());
            user_type_Address.setText(user.getAddress());
        } else {
        JOptionPane.showMessageDialog(this, "Unable to load user data");
    }
}

    private void setEditable(boolean value) {
        user_type_Full_Name.setEditable(value);
        user_type_contact.setEditable(value);
        user_type_Email.setEditable(value);
        user_type_Address.setEditable(value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        box = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        Full_Name = new javax.swing.JLabel();
        user_type_Full_Name = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        user_username_ = new javax.swing.JTextField();
        Contact = new javax.swing.JLabel();
        user_type_contact = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        user_type_Email = new javax.swing.JTextField();
        Address = new javax.swing.JLabel();
        user_type_Address = new javax.swing.JTextField();
        Update_Profile = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        box.setBackground(new java.awt.Color(57, 174, 221));
        box.setLayout(null);

        Heading.setBackground(new java.awt.Color(43, 219, 43));
        Heading.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading.setText("My Account");
        Heading.setOpaque(true);
        box.add(Heading);
        Heading.setBounds(100, 20, 300, 50);

        Full_Name.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Full_Name.setText("Full Name                :");
        box.add(Full_Name);
        Full_Name.setBounds(20, 100, 140, 35);

        user_type_Full_Name.addActionListener(this::user_type_Full_NameActionPerformed);
        box.add(user_type_Full_Name);
        user_type_Full_Name.setBounds(170, 100, 310, 35);

        username.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        username.setText("username_              :");
        box.add(username);
        username.setBounds(20, 160, 140, 35);

        user_username_.addActionListener(this::user_username_ActionPerformed);
        box.add(user_username_);
        user_username_.setBounds(170, 160, 310, 35);

        Contact.setText("Contact no.               :");
        box.add(Contact);
        Contact.setBounds(20, 220, 140, 35);
        box.add(user_type_contact);
        user_type_contact.setBounds(170, 220, 310, 35);

        Email.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Email.setText("Email                       :");
        box.add(Email);
        Email.setBounds(20, 280, 140, 35);
        box.add(user_type_Email);
        user_type_Email.setBounds(170, 280, 310, 35);

        Address.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Address.setText("Address                   :");
        box.add(Address);
        Address.setBounds(20, 340, 140, 35);
        box.add(user_type_Address);
        user_type_Address.setBounds(170, 340, 310, 35);

        Update_Profile.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Update_Profile.setText("Update Profile");
        Update_Profile.addActionListener(this::Update_ProfileActionPerformed);
        box.add(Update_Profile);
        Update_Profile.setBounds(150, 410, 190, 50);

        Cancel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(this::CancelActionPerformed);
        box.add(Cancel);
        Cancel.setBounds(170, 465, 150, 30);

        Logout.setBackground(new java.awt.Color(43, 219, 43));
        Logout.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(this::LogoutActionPerformed);
        box.add(Logout);
        Logout.setBounds(170, 500, 150, 40);

        getContentPane().add(box, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_type_Full_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_type_Full_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_type_Full_NameActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void Update_ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_ProfileActionPerformed
        if (!editing) {
        editing = true;
        Update_Profile.setText("Save");
        Cancel.setVisible(true);

        originalFullName = user_type_Full_Name.getText();
        originalContact = user_type_contact.getText();
        originalEmail = user_type_Email.getText();
        originalAddress = user_type_Address.getText();

        setEditable(true);
        return;
    }

    UserAccount user = new UserAccount();
    user.setUsername(loggedInUsername);
    user.setFullName(user_type_Full_Name.getText().trim());
    user.setContact(user_type_contact.getText().trim());
    user.setEmail(user_type_Email.getText().trim());
    user.setAddress(user_type_Address.getText().trim());

    var result = controller.update(user);

    JOptionPane.showMessageDialog(this, result.getMessage());

    if (result.isSuccess()) {
        editing = false;
        Update_Profile.setText("Update Profile");
        Cancel.setVisible(false);
        setEditable(false);
    }
    }//GEN-LAST:event_Update_ProfileActionPerformed

    private void user_username_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_username_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_username_ActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        user_type_Full_Name.setText(originalFullName);
        user_type_contact.setText(originalContact);
        user_type_Email.setText(originalEmail);
        user_type_Address.setText(originalAddress);

        editing = false;
        Update_Profile.setText("Update Profile");
        Cancel.setVisible(false);
        setEditable(false);
    }//GEN-LAST:event_CancelActionPerformed

public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(() -> {
        new User_Manage_Account("testuser").setVisible(true);
    });
}

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel Contact;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Full_Name;
    private javax.swing.JLabel Heading;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Update_Profile;
    private javax.swing.JPanel box;
    private javax.swing.JTextField user_type_Address;
    private javax.swing.JTextField user_type_Email;
    private javax.swing.JTextField user_type_Full_Name;
    private javax.swing.JTextField user_type_contact;
    private javax.swing.JTextField user_username_;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
