/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Color;
import UserController.booknowController;



public class User_vehicleicon extends javax.swing.JPanel {

    private javax.swing.JFrame mainFrame;
    private int companyId;
    private String vehicleName;
    private double priceValue; 
    private int loggedInUserId; 
    private int vehicleDbId;
    private java.util.function.Consumer<User_vehicleicon> onButtonClick;

   
    public User_vehicleicon() {
        initComponents();
        this.setPreferredSize(new java.awt.Dimension(200, 250));
    }

    public int getVehicleDbId() { return this.vehicleDbId; }
    
    // Moved this OUTSIDE of other methods
    public java.util.function.Consumer<User_vehicleicon> getOnButtonClick() { 
        return this.onButtonClick; 
    }

    // --- SETTERS ---
    public void setVehicleDbId(int id) { this.vehicleDbId = id; }
    public void setLoggedInUserId(int userId) { this.loggedInUserId = userId; }
    public void setMainFrame(javax.swing.JFrame frame) { this.mainFrame = frame; }
    public void setOnAction(java.util.function.Consumer<User_vehicleicon> action) { this.onButtonClick = action; }
    public void setCompanyId(int companyId) { this.companyId = companyId; }
    
    public void setVehicleName(String name) {
        this.vehicleName = name;
        jLabel2.setText("Model: " + name);
    }

    public void setPriceValue(double price) {
        this.priceValue = price;
        jLabel3.setText(String.format("Price : Rs. %.2f/day", price)); 
    }

    public void setCustomIcon(javax.swing.ImageIcon icon) {
        if (icon != null) {
            java.awt.Image img = icon.getImage().getScaledInstance(160, 90, java.awt.Image.SCALE_SMOOTH);
            jLabel1.setIcon(new javax.swing.ImageIcon(img));
            jLabel1.setText("");
        }
    }

    public void setAvailability(String status) {
        if (status == null) return;
        String lowerStatus = status.toLowerCase();
        switch (lowerStatus) {
            case "booked":
            case "maintenance":
                view.setText(status.toUpperCase());
                view.setBackground(java.awt.Color.GRAY);
                view.setForeground(java.awt.Color.WHITE);
                view.setEnabled(false);
                break;
            default: // available
                view.setText("View");
                view.setBackground(new java.awt.Color(102, 255, 102));
                view.setForeground(java.awt.Color.BLACK);
                view.setEnabled(true);
                break;
        }
    }

      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        view = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));
        setMaximumSize(new java.awt.Dimension(160, 198));
        setMinimumSize(new java.awt.Dimension(160, 198));
        setPreferredSize(new java.awt.Dimension(160, 198));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("                 photo");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jLabel1.setMaximumSize(new java.awt.Dimension(90, 25));
        jLabel1.setMinimumSize(new java.awt.Dimension(90, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(90, 25));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 90));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Name  :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 170, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Price   :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 170, -1));

        view.setBackground(new java.awt.Color(102, 255, 102));
        view.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        view.setText("view");
        view.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 70, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
      // The View just passes itself to the Controller
        booknowController controller = new booknowController();
        controller.processIconClick(this);
    
    // 2. DELETE everything else that was below this line!
    // Do not perform SQL queries or create JFrames here.

    }//GEN-LAST:event_viewActionPerformed
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables

    
}
   

