/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author hp
 */
public class vehicleDetail extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vehicleDetail.class.getName());

    /**
     * Creates new form vehicleDetail
     */
    public vehicleDetail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        brand = new javax.swing.JLabel();
        model = new javax.swing.JLabel();
        vehicletype = new javax.swing.JLabel();
        colour = new javax.swing.JLabel();
        numberplate = new javax.swing.JLabel();
        booknow = new javax.swing.JButton();
        frontphoto = new javax.swing.JLabel();
        sidephoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(null);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Brand              :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 60, 110, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Vehicle details");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(110, 10, 180, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("model              :  ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 100, 115, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Vehicle  Type  :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 140, 110, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Colour              :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 180, 105, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Number Plate  :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 220, 110, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Price                 :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 260, 106, 20);

        price.setText("hlo");
        jPanel2.add(price);
        price.setBounds(150, 260, 140, 20);

        brand.setText("hlo");
        jPanel2.add(brand);
        brand.setBounds(150, 60, 140, 20);

        model.setText("hlo");
        jPanel2.add(model);
        model.setBounds(150, 100, 140, 20);

        vehicletype.setText("hlo");
        jPanel2.add(vehicletype);
        vehicletype.setBounds(150, 140, 140, 20);

        colour.setText("hlo");
        jPanel2.add(colour);
        colour.setBounds(150, 180, 140, 20);

        numberplate.setText("hlo");
        jPanel2.add(numberplate);
        numberplate.setBounds(150, 220, 140, 20);

        booknow.setBackground(new java.awt.Color(102, 255, 102));
        booknow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        booknow.setText("Book Now");
        booknow.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        booknow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booknowActionPerformed(evt);
            }
        });
        jPanel2.add(booknow);
        booknow.setBounds(120, 340, 130, 24);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 30, 400, 470);

        frontphoto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        frontphoto.setForeground(new java.awt.Color(255, 255, 255));
        frontphoto.setText("               Front photo with number plate");
        frontphoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        frontphoto.setMinimumSize(new java.awt.Dimension(400, 300));
        frontphoto.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel1.add(frontphoto);
        frontphoto.setBounds(500, 10, 400, 300);

        sidephoto.setBackground(new java.awt.Color(255, 255, 255));
        sidephoto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sidephoto.setForeground(new java.awt.Color(255, 255, 255));
        sidephoto.setText("                               Side photo  ");
        sidephoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        sidephoto.setMaximumSize(new java.awt.Dimension(400, 300));
        sidephoto.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel1.add(sidephoto);
        sidephoto.setBounds(500, 330, 400, 300);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 920, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void booknowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booknowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booknowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vehicleDetail().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton booknow;
    private javax.swing.JLabel brand;
    private javax.swing.JLabel colour;
    private javax.swing.JLabel frontphoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel model;
    private javax.swing.JLabel numberplate;
    private javax.swing.JLabel price;
    private javax.swing.JLabel sidephoto;
    private javax.swing.JLabel vehicletype;
    // End of variables declaration//GEN-END:variables
}
