/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import dao.VehicleBookingDao;
import model.VehicleBooking;
import javax.swing.JOptionPane;
import java.sql.Date;


/**
 *
 * @author WELCOME
 */
public class Vehicle_booking_form extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vehicle_booking_form.class.getName());

    /**
     * Creates new form Vehicle_booking_form
     */
    public Vehicle_booking_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        vehicle_booking_form = new javax.swing.JLabel();
        customer_details = new javax.swing.JLabel();
        full_name = new javax.swing.JLabel();
        phone_number = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        province = new javax.swing.JLabel();
        booking_details = new javax.swing.JLabel();
        pickup_date = new javax.swing.JLabel();
        pickup_location = new javax.swing.JLabel();
        return_date = new javax.swing.JLabel();
        return_location = new javax.swing.JLabel();
        pickup_time = new javax.swing.JLabel();
        rental_duration = new javax.swing.JLabel();
        return_time = new javax.swing.JLabel();
        email_ = new javax.swing.JTextField();
        fullname = new javax.swing.JTextField();
        phonenumber = new javax.swing.JTextField();
        address_ = new javax.swing.JTextField();
        city_ = new javax.swing.JTextField();
        pickupdate = new javax.swing.JTextField();
        pickuplocation = new javax.swing.JTextField();
        returndate = new javax.swing.JTextField();
        returnlocation = new javax.swing.JTextField();
        returntime = new javax.swing.JTextField();
        rentalduration = new javax.swing.JTextField();
        pickuptime = new javax.swing.JTextField();
        province_ = new javax.swing.JTextField();
        driver_option = new javax.swing.JLabel();
        driver_licence = new javax.swing.JLabel();
        driverlicence = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        self_drive = new javax.swing.JRadioButton();
        with_driver = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(null);

        vehicle_booking_form.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        vehicle_booking_form.setText("Vehicle Booking Form");
        jPanel1.add(vehicle_booking_form);
        vehicle_booking_form.setBounds(520, 0, 350, 90);

        customer_details.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        customer_details.setText("Customer Details");
        jPanel1.add(customer_details);
        customer_details.setBounds(280, 110, 170, 16);

        full_name.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        full_name.setText("Full Name");
        jPanel1.add(full_name);
        full_name.setBounds(310, 160, 60, 20);

        phone_number.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        phone_number.setText("Phone Number");
        jPanel1.add(phone_number);
        phone_number.setBounds(290, 200, 90, 16);

        address.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        address.setText("Address");
        jPanel1.add(address);
        address.setBounds(310, 240, 50, 16);

        city.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        city.setText("City");
        jPanel1.add(city);
        city.setBounds(320, 280, 30, 16);

        email.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        email.setText("E-mail");
        jPanel1.add(email);
        email.setBounds(770, 200, 34, 16);

        province.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        province.setText("Province");
        jPanel1.add(province);
        province.setBounds(750, 280, 50, 16);

        booking_details.setFont(new java.awt.Font("MV Boli", 3, 18)); // NOI18N
        booking_details.setText("Booking Details");
        jPanel1.add(booking_details);
        booking_details.setBounds(260, 340, 150, 25);

        pickup_date.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        pickup_date.setText("Pickup Date");
        jPanel1.add(pickup_date);
        pickup_date.setBounds(280, 390, 70, 16);

        pickup_location.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        pickup_location.setText("Pickup Location");
        jPanel1.add(pickup_location);
        pickup_location.setBounds(270, 430, 90, 16);

        return_date.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        return_date.setText("Return Date");
        jPanel1.add(return_date);
        return_date.setBounds(280, 470, 70, 16);

        return_location.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        return_location.setText("Return Location");
        jPanel1.add(return_location);
        return_location.setBounds(270, 510, 90, 16);

        pickup_time.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        pickup_time.setText("Pickup-Time");
        jPanel1.add(pickup_time);
        pickup_time.setBounds(740, 390, 70, 16);

        rental_duration.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        rental_duration.setText("Rental Duration");
        jPanel1.add(rental_duration);
        rental_duration.setBounds(730, 430, 90, 16);

        return_time.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        return_time.setText("Return Time");
        jPanel1.add(return_time);
        return_time.setBounds(730, 470, 70, 16);

        email_.addActionListener(this::email_ActionPerformed);
        jPanel1.add(email_);
        email_.setBounds(820, 200, 260, 30);

        fullname.addActionListener(this::fullnameActionPerformed);
        jPanel1.add(fullname);
        fullname.setBounds(380, 160, 250, 30);

        phonenumber.addActionListener(this::phonenumberActionPerformed);
        jPanel1.add(phonenumber);
        phonenumber.setBounds(380, 200, 250, 30);

        address_.addActionListener(this::address_ActionPerformed);
        jPanel1.add(address_);
        address_.setBounds(380, 240, 700, 30);

        city_.addActionListener(this::city_ActionPerformed);
        jPanel1.add(city_);
        city_.setBounds(380, 280, 260, 30);

        pickupdate.addActionListener(this::pickupdateActionPerformed);
        jPanel1.add(pickupdate);
        pickupdate.setBounds(380, 390, 250, 30);

        pickuplocation.addActionListener(this::pickuplocationActionPerformed);
        jPanel1.add(pickuplocation);
        pickuplocation.setBounds(380, 430, 250, 30);

        returndate.addActionListener(this::returndateActionPerformed);
        jPanel1.add(returndate);
        returndate.setBounds(380, 470, 250, 30);

        returnlocation.addActionListener(this::returnlocationActionPerformed);
        jPanel1.add(returnlocation);
        returnlocation.setBounds(380, 510, 250, 30);

        returntime.addActionListener(this::returntimeActionPerformed);
        jPanel1.add(returntime);
        returntime.setBounds(820, 470, 260, 30);

        rentalduration.addActionListener(this::rentaldurationActionPerformed);
        jPanel1.add(rentalduration);
        rentalduration.setBounds(820, 430, 260, 30);

        pickuptime.addActionListener(this::pickuptimeActionPerformed);
        jPanel1.add(pickuptime);
        pickuptime.setBounds(820, 390, 260, 30);

        province_.addActionListener(this::province_ActionPerformed);
        jPanel1.add(province_);
        province_.setBounds(820, 280, 260, 30);

        driver_option.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        driver_option.setText("Driver Option:");
        jPanel1.add(driver_option);
        driver_option.setBounds(240, 540, 110, 20);

        driver_licence.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        driver_licence.setText("Driver Licence No.(If Self -Drive) :");
        jPanel1.add(driver_licence);
        driver_licence.setBounds(250, 620, 190, 16);
        jPanel1.add(driverlicence);
        driverlicence.setBounds(440, 620, 510, 30);

        ok.setBackground(new java.awt.Color(51, 153, 0));
        ok.setFont(new java.awt.Font("Broadway", 3, 14)); // NOI18N
        ok.setForeground(new java.awt.Color(204, 255, 255));
        ok.setText("OK");
        ok.addActionListener(this::okActionPerformed);
        jPanel1.add(ok);
        ok.setBounds(660, 660, 72, 24);

        self_drive.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        self_drive.setText("Self-Drive");
        self_drive.addActionListener(this::self_driveActionPerformed);
        jPanel1.add(self_drive);
        self_drive.setBounds(310, 570, 98, 21);

        with_driver.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        with_driver.setText("With-Driver");
        with_driver.addActionListener(this::with_driverActionPerformed);
        jPanel1.add(with_driver);
        with_driver.setBounds(210, 570, 90, 21);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        setBounds(0, 0, 1294, 728);
    }// </editor-fold>//GEN-END:initComponents

    private void email_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_ActionPerformed

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void phonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenumberActionPerformed

    private void address_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_ActionPerformed

    private void city_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_city_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_city_ActionPerformed

    private void pickupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pickupdateActionPerformed

    private void pickuplocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickuplocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pickuplocationActionPerformed

    private void returndateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returndateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returndateActionPerformed

    private void returnlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnlocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnlocationActionPerformed

    private void returntimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returntimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returntimeActionPerformed

    private void rentaldurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentaldurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentaldurationActionPerformed

    private void pickuptimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickuptimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pickuptimeActionPerformed

    private void province_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_province_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_province_ActionPerformed

    private void self_driveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_self_driveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_self_driveActionPerformed

    private void with_driverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_with_driverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_with_driverActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        try {
        VehicleBooking v = new VehicleBooking();

        v.fullName = fullname.getText();
        v.phone = phonenumber.getText();
        v.email = email_.getText();
        v.address = address_.getText();
        v.city = city_.getText();
        v.province = province_.getText();

        v.pickupDate = Date.valueOf(pickupdate.getText());
        v.pickupTime = pickuptime.getText();
        v.pickupLocation = pickuplocation.getText();

        v.returnDate = Date.valueOf(returndate.getText());
        v.returnTime = returntime.getText();
        v.returnLocation = returnlocation.getText();

        v.rentalDuration = rentalduration.getText();

        if (self_drive.isSelected()) {
            v.driverOption = "Self-Drive";
            v.driverLicence = driverlicence.getText();
        } else if (with_driver.isSelected()) {
            v.driverOption = "With-Driver";
            v.driverLicence = "";
        } else {
            JOptionPane.showMessageDialog(this, "Please select driver option");
            return;
        }

        VehicleBookingDao dao = new VehicleBookingDao();

        if (dao.insert(v)) {
            JOptionPane.showMessageDialog(this, "Booking Saved Successfully!");
        } else {
            JOptionPane.showMessageDialog(this, "Error while saving booking!");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Please check date format (yyyy-mm-dd)");
    }
    }//GEN-LAST:event_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Vehicle_booking_form().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField address_;
    private javax.swing.JLabel booking_details;
    private javax.swing.JLabel city;
    private javax.swing.JTextField city_;
    private javax.swing.JLabel customer_details;
    private javax.swing.JLabel driver_licence;
    private javax.swing.JLabel driver_option;
    private javax.swing.JTextField driverlicence;
    private javax.swing.JLabel email;
    private javax.swing.JTextField email_;
    private javax.swing.JLabel full_name;
    private javax.swing.JTextField fullname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ok;
    private javax.swing.JLabel phone_number;
    private javax.swing.JTextField phonenumber;
    private javax.swing.JLabel pickup_date;
    private javax.swing.JLabel pickup_location;
    private javax.swing.JLabel pickup_time;
    private javax.swing.JTextField pickupdate;
    private javax.swing.JTextField pickuplocation;
    private javax.swing.JTextField pickuptime;
    private javax.swing.JLabel province;
    private javax.swing.JTextField province_;
    private javax.swing.JLabel rental_duration;
    private javax.swing.JTextField rentalduration;
    private javax.swing.JLabel return_date;
    private javax.swing.JLabel return_location;
    private javax.swing.JLabel return_time;
    private javax.swing.JTextField returndate;
    private javax.swing.JTextField returnlocation;
    private javax.swing.JTextField returntime;
    private javax.swing.JRadioButton self_drive;
    private javax.swing.JLabel vehicle_booking_form;
    private javax.swing.JRadioButton with_driver;
    // End of variables declaration//GEN-END:variables
}
