/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author WELCOME
 */
public class Booking_Form extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Booking_Form.class.getName());

    /**
     * Creates new form Booking_Form
     */
    public Booking_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        return_date = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        full_name = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        phone_number = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        pickup_date = new javax.swing.JLabel();
        pickup_location = new javax.swing.JLabel();
        pickup_time = new javax.swing.JLabel();
        rental_duration = new javax.swing.JLabel();
        return_time = new javax.swing.JLabel();
        driver_licence = new javax.swing.JLabel();
        province = new javax.swing.JLabel();
        customer_details = new javax.swing.JLabel();
        booking_details = new javax.swing.JLabel();
        with_driver = new javax.swing.JLabel();
        self_drive = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel3.setLayout(null);

        jTextField2.setBorder(null);
        jTextField2.addActionListener(this::jTextField2ActionPerformed);
        jPanel3.add(jTextField2);
        jTextField2.setBounds(290, 140, 250, 20);

        jTextField4.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        jTextField4.setBorder(null);
        jTextField4.addActionListener(this::jTextField4ActionPerformed);
        jPanel3.add(jTextField4);
        jTextField4.setBounds(290, 170, 750, 20);

        jTextField3.setBorder(null);
        jPanel3.add(jTextField3);
        jTextField3.setBounds(790, 140, 250, 20);

        jTextField5.setBorder(null);
        jTextField5.addActionListener(this::jTextField5ActionPerformed);
        jPanel3.add(jTextField5);
        jTextField5.setBounds(290, 200, 250, 20);

        jTextField1.setBorder(null);
        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        jPanel3.add(jTextField1);
        jTextField1.setBounds(290, 110, 250, 20);

        jTextField6.setBorder(null);
        jTextField6.addActionListener(this::jTextField6ActionPerformed);
        jPanel3.add(jTextField6);
        jTextField6.setBounds(790, 200, 250, 20);

        jPanel8.setBackground(new java.awt.Color(0, 153, 51));
        jPanel8.setForeground(new java.awt.Color(51, 153, 0));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Driver Option");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel8);
        jPanel8.setBounds(240, 440, 100, 20);

        jTextField8.setBorder(null);
        jTextField8.addActionListener(this::jTextField8ActionPerformed);
        jPanel3.add(jTextField8);
        jTextField8.setBounds(290, 300, 250, 20);

        jTextField9.setBorder(null);
        jTextField9.addActionListener(this::jTextField9ActionPerformed);
        jPanel3.add(jTextField9);
        jTextField9.setBounds(290, 340, 250, 20);

        jTextField10.setBorder(null);
        jTextField10.addActionListener(this::jTextField10ActionPerformed);
        jPanel3.add(jTextField10);
        jTextField10.setBounds(290, 380, 250, 20);

        jTextField7.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        jTextField7.setBorder(null);
        jPanel3.add(jTextField7);
        jTextField7.setBounds(780, 380, 260, 20);

        jTextField12.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        jTextField12.setBorder(null);
        jPanel3.add(jTextField12);
        jTextField12.setBounds(780, 300, 260, 20);

        jTextField13.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        jTextField13.setBorder(null);
        jPanel3.add(jTextField13);
        jTextField13.setBounds(780, 340, 260, 20);

        return_date.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        return_date.setText("Return Date");
        jPanel3.add(return_date);
        return_date.setBounds(200, 380, 70, 20);

        jTextField14.setBorder(null);
        jTextField14.addActionListener(this::jTextField14ActionPerformed);
        jPanel3.add(jTextField14);
        jTextField14.setBounds(420, 540, 490, 20);

        jLabel2.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        jLabel2.setText("VEHICLE BOOKING FORM");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jLabel2);
        jLabel2.setBounds(510, 10, 360, 50);

        Submit.setBackground(new java.awt.Color(0, 153, 0));
        Submit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(this::SubmitActionPerformed);
        jPanel3.add(Submit);
        Submit.setBounds(600, 590, 110, 27);

        full_name.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        full_name.setText("Full Name");
        jPanel3.add(full_name);
        full_name.setBounds(210, 110, 70, 14);

        email.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        email.setText("E-mail");
        jPanel3.add(email);
        email.setBounds(720, 140, 31, 14);

        phone_number.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        phone_number.setText("Phone Number");
        jPanel3.add(phone_number);
        phone_number.setBounds(200, 140, 90, 14);

        address.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        address.setText("Address");
        jPanel3.add(address);
        address.setBounds(220, 170, 52, 14);

        city.setBackground(new java.awt.Color(255, 255, 255));
        city.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        city.setText("City");
        jPanel3.add(city);
        city.setBounds(230, 200, 28, 14);

        pickup_date.setBackground(new java.awt.Color(255, 255, 255));
        pickup_date.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        pickup_date.setText("Pickup Date");
        jPanel3.add(pickup_date);
        pickup_date.setBounds(190, 300, 70, 14);

        pickup_location.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        pickup_location.setText("Pickup Location");
        jPanel3.add(pickup_location);
        pickup_location.setBounds(190, 340, 100, 14);

        pickup_time.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        pickup_time.setText("Pickup Time");
        jPanel3.add(pickup_time);
        pickup_time.setBounds(690, 300, 70, 14);

        rental_duration.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        rental_duration.setText("Rental Duration");
        jPanel3.add(rental_duration);
        rental_duration.setBounds(680, 340, 90, 14);

        return_time.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        return_time.setText("Return Time");
        jPanel3.add(return_time);
        return_time.setBounds(690, 380, 70, 14);

        driver_licence.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        driver_licence.setText("Driver Licence No.(If self Drive):");
        jPanel3.add(driver_licence);
        driver_licence.setBounds(210, 540, 210, 16);

        province.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        province.setText("Province");
        jPanel3.add(province);
        province.setBounds(710, 200, 52, 14);

        customer_details.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        customer_details.setText("Customer Details");
        jPanel3.add(customer_details);
        customer_details.setBounds(190, 60, 130, 20);

        booking_details.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        booking_details.setText("BOOKING DETAILS");
        jPanel3.add(booking_details);
        booking_details.setBounds(180, 256, 130, 20);

        with_driver.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        with_driver.setText("With Driver");
        jPanel3.add(with_driver);
        with_driver.setBounds(200, 480, 80, 16);

        self_drive.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        self_drive.setText("Self-Drive");
        jPanel3.add(self_drive);
        self_drive.setBounds(300, 480, 70, 16);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1300, 750);

        setBounds(0, 0, 1294, 728);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Booking_Form().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JLabel address;
    private javax.swing.JLabel booking_details;
    private javax.swing.JLabel city;
    private javax.swing.JLabel customer_details;
    private javax.swing.JLabel driver_licence;
    private javax.swing.JLabel email;
    private javax.swing.JLabel full_name;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel phone_number;
    private javax.swing.JLabel pickup_date;
    private javax.swing.JLabel pickup_location;
    private javax.swing.JLabel pickup_time;
    private javax.swing.JLabel province;
    private javax.swing.JLabel rental_duration;
    private javax.swing.JLabel return_date;
    private javax.swing.JLabel return_time;
    private javax.swing.JLabel self_drive;
    private javax.swing.JLabel with_driver;
    // End of variables declaration//GEN-END:variables
}
